### ISSUE TITLE
class methods instead of functions

### ISSUE THREAD

**Issue by parneshraniga** [peiffer-innovations/json_dynamic_widget#103]
Apologies if this is already in the docs somewhere that I missed. Is it possible to pass an object (via registry) and then call methods on it? 

In my use case, the dynamics widgets are stateless (all will be forms ) and I want to pass in a "presenter" type object on which function calls to update the data will be made.

**Comment by crisperit** [comment]
Well... afaik it is not possible 
We're integrated with `expressions` package which has sth like getting the object members - but calling the methods is rather not sth possible out of the box 
https://github.com/appsup-dart/expressions/blob/master/lib/src/evaluator.dart#L101-L107 

You can implement your own `ArgProcessor` or register a set of functions which will take presenter as a variable by name and call specific function

```
'${presenter_updateCountry(presenter, country)}'
```

**Comment by jpeiffer** [comment]
Can you give an example of what you'd like to do? I think that can map out a better answer.

I think @crisperit was on the right track with his suggestion. This package uses a more advanced expressions package, https://pub.dev/packages/template_expressions, than he called out (though derived from for sure) though, and that might help.

You can register any function you want via the context. Or take a look at the registry to add your own class level extensions.

**Comment by parneshraniga** [comment]
In my app, I have a page where amongst other things, I want to present a form. Depending on the context, these will be different forms and this is where the current package is very useful. 

My app is based on `stacked` (https://pub.dev/packages/stacked) which is essentially a MVVM /MVP type design. 

On change or submit, I wanted to update the data in the viewmodel and/or handle the submission and therefore wondered if I can call a method.

However, I had a closer look at the form example (with save context and validators) and I think that might be a better way to go at the moment even though strictly speaking it breaks the statelessness. 

To handle the submission, I will just register a function that takes the viewmodel as an input.

Will let you know if it doesn't work.

Thanks for getting back so quickly and for the project. It's really nice.

**Comment by parneshraniga** [comment]
We can consider this closed. The form fields save to the registry when provided an ID and I can provide a function wrapper for the viewmodel handler for submit which can grab these from the registry.
