### ISSUE TITLE
Issue in writing JSON for Transform.rotate() widget

### ISSUE THREAD

**Issue by kalpeshmayani** [peiffer-innovations/json_dynamic_widget#115]
Need help to write JSON for Transform.rotate() widget

`Transform.rotate(
          angle: -0.075,
          child: Text(
            "Wednesday",
          ),
        )`

Can anyone suggest correct JSON for above widget?

**Comment by jpeiffer** [comment]
Transform isn't one of the supported widgets.

You can see the full list here:
https://github.com/peiffer-innovations/json_dynamic_widget#built-in-widgets

If you'd like to add Transform, PRs are welcome, or you can use these instructions to custom add it to your app:
https://github.com/peiffer-innovations/json_dynamic_widget#creating-custom-widgets
