### ISSUE TITLE
dynamic builder takes builderType with default properties 

### ISSUE THREAD

**Issue by munibz** [peiffer-innovations/json_dynamic_widget#116]
The dynamic builder function takes only the name of builder type and not it's properties, 

For eg. i wanted to build a horizontal listview as posted in the example below but i couldn't use that because the function takes only the name of builder type, Could the dynamic builder type parameter be modified to take jsonwidgetdata instead of a string and build it with it's properties 

Eg where i have a horizontal list of images being added from gallery 

![Screenrecorder-2022-12-19-10-41-22-431_AdobeExpress](https://user-images.githubusercontent.com/81231153/208353830-a59be9c2-bd4b-4f39-8dd8-47ae2f612e00.gif)

**Comment by crisperit** [comment]
Hello!
That's not true. This is not shown in the example but as you can see in here
https://github.com/peiffer-innovations/json_dynamic_widget/blob/main/lib/src/builders/json_dynamic_builder.dart#L52-L58

Dynamic builder is replacing type into "dynamic.builderType" and as the args it takes all besides ``"dynamic"`

So if you want it horizontally then:
```
{
   "type": "dynamic",
   "args": {
         "dynamic": {
              "builderType": "list_view",
              "childTemplate": {...},
         },
         "scrollDirection": "horizontal",
         ...other list_biew properties
         ""
}
```

So all list_view properties should go as `dynamic` builder args

@munibz Let me know if that fixes your issue

**Comment by munibz** [comment]
Thanks for helping out didn't know that it worked liked that, tried passing the args inside dynamic object, and it worked thanks once again :)
