### ISSUE TITLE
tricky listview issue that caused some pain

### ISSUE THREAD

**Issue by aktxyz** [peiffer-innovations/json_dynamic_widget#125]
I have a listview inside the body of a nestedscrollview ... and the scrolling behavior of the list view did not match the scrolling behavior of  the same widget tree created directly with dart/flutter.  Basically the listview would scroll and NOT collapse the nestedscrollview header.

After much digging and learning (which was quite fun) ... I think I found the main culprit ... the default value of ListView.primary.

In the link below you can see the default value of primary for the "normal" scenario is true.  So basically adding the primary=true to the args makes it work just fine :)

https://github.com/flutter/flutter/blob/06979d4e2e9a8c5dc8b37a07965ce4cd01b41caf/packages/flutter/lib/src/widgets/scroll_view.dart#L74

Explicitly adding primary=true is no problem ... but it may be better to add some logic to the builder for this case.  Something like this maybe:

```
      if (result.controller == null && result.scrollDirection == Axis.vertical) {
        result.primary = true;
      }
```

**Comment by jpeiffer** [comment]
Please provide a sample app to reproduce the issue.

**Comment by jpeiffer** [comment]
Closing for lack of response.
