### ISSUE TITLE
Register function not work

### ISSUE THREAD

**Issue by scroollocker** [peiffer-innovations/json_dynamic_widget#127]
Hello,
This part of code is not called from json button: 

`_registry.registerFunctions({
      'getWeather': ({args, required registry}) {
        int rand = Random().nextInt(30);

        registry.setValue(
          'weather',
          '+$rand°C',
        );
      },
    });`

My json implementation of button:

`{
                "type": "text_button",
                "id": "press_me_button",
                "args": {
                    "onPressed": "${getWeather()}"
                },
                "child": {
                    "type": "align",
                    "args": {
                        "alignment": "centerRight"
                    },
                    "child": {
                        "type": "text",
                        "args": {
                            "text": "Update"
                        }
                    }
                }
            }`

In the debugger, I see that the function is called several times when building the interface. But it does not work when called through a button.

but if i change to "onPressed": "${set_value('weather', '+30' )}" it work fine

**Comment by crisperit** [comment]
You should define the function like that:
```
    'getWeather': ({args, required registry}) => () {
          int rand = Random().nextInt(30);

          registry.setValue(
            'weather',
            '+$rand°C',
          );
        },
```

For now your function is called at the render time. 

By adding `=>() {...}` the render part will only generate a callable function fitted to be used by `onPressed`

**Comment by jpeiffer** [comment]
I'm going to close this.  Please re-open or create a new issue if the problem persists after @crisperit 's answer.
