### ISSUE TITLE
How to create separate registry per page to set dynamic values on the registry to prevent the values from one page being overwritten by another

### ISSUE THREAD

**Issue by kpinfosoft** [peiffer-innovations/json_dynamic_widget#130]
Hello,

I am using JsonWidgetData inside CarouselSlider builder but it is overwritten pages with one another. And through documentation I came to know that we can prevent the values from one page being overwritten by another by creating separate registry per page.

Can anyone please tell how to create separate registry per page?

**Comment by crisperit** [comment]
Well, by default everything is using a default registry instance
https://github.com/peiffer-innovations/json_dynamic_widget/blob/main/lib/src/components/json_widget_registry.dart#L61-L63

So you just have to create `JsonWidgetRegistry` instance by calling its constructor for each of the page
