### ISSUE TITLE
Is it possible to use a async function and display a picker?

### ISSUE THREAD

**Issue by gredajustyna** [peiffer-innovations/json_dynamic_widget#132]
Hello, 
I am developing a form using this library and i have a question. I'd like to show a date picker from `intl` package in order to let user select a date of birth. I keep context in the registry. But when i call the date picker, i get the following error:
`type 'Future<dynamic>' is not a subtype of type '(() => void)?'`

Is it possible to await a value from a picker using this library? Are such async functions supported?

**Comment by gredajustyna** [comment]
Thanks a lot - that's exactly what I needed to make it work!

**Comment by crisperit** [comment]
Glad that I could help! Closing
