### ISSUE TITLE
advice on dynamically updating some widgets in the tree

### ISSUE THREAD

**Issue by aktxyz** [peiffer-innovations/json_dynamic_widget#138]
I have a widget hierarchy that contains a list of items ... some of the items are being shown with a spinner to indicate that the content of the item is still pending ... and I will get fresh data for those items soon via a web socket.

Via websocket, I get a list of json fragments that contain the fresh data for these pending items.

Do you have any advice/recommendation about merging those items into the FullWidgetPage tree where just those updated items get redrawn?

Looking at things like for_each, dynamic, setWidgetByKey, etc ... I bet there is an good/easy way to do this.

**Comment by aktxyz** [comment]
One attempt I made was to have a ```set_widget``` item that defines widget1 and widget2.
I then display these in a list with ...

```
"${widget1}",
"${widget2}",
```

I then update the registry via an onTap on a button like this ...

```
          var registry = JsonWidgetRegistry.instance;
          var json = '''
{
  "type": "container",
  "args": {
    "padding": "20",
    "margin": "20",
    "color": "#88F"
  },
  "child": {
    "type": "text",
    "args": {
      "text": "widget1_data !!"
    }
  }
}
'''
              .trim();
          var data = JsonWidgetData.fromDynamic(
            json,
            registry: registry,
          );
          registry.setValue('widget1', data);
```

I step thru the code and see in the ```setValue``` function the ```valueStreamController``` is updated ... BUT ... the widget1 display does not update with the new UI definition.

For some reason, the widget references are not listening it seems?

```
"${widget1}",
"${widget2}",
```

**Comment by aktxyz** [comment]
Hmm ... this seemed to work by adding a ```listen``` to the container that wrapped my ```set_widget``` widget

```
                                {
                                  "type": "container",
                                  "child": "${widget1}",
                                  "listen": [
                                    "widget1"
                                  ]
                                },
```

instead of just

```
                                {
                                  "type": "container",
                                  "child": "${widget1}",
                                },
```

**Comment by jpeiffer** [comment]
Ah, correct.  You have to tell the engine what to listen to changes on.  It's more expensive to listen to variables for changes so the default setup is to not listen unless explicitly told to.

**Comment by aktxyz** [comment]
make sense ... thanks !
