### ISSUE TITLE
bottomNavigationBar

### ISSUE THREAD

**Issue by aktxyz** [peiffer-innovations/json_dynamic_widget#139]
Hello !  I see a reference to bottomNavigationBar in the example ...

https://github.com/peiffer-innovations/json_dynamic_widget/blob/959894e8b054c3e8f67add8b2decaa8afc231654/lib/src/builders/json_scaffold_builder.dart#L125

but I actually don't see a builder for it ... am I missing something ?

**Comment by aktxyz** [comment]
Hmm ... I struggled a bit today trying to get a BottomNavigationBar builder working ... was hoping for some guidance.

I am stuck on the BottomNavigationBarItem ... I tried making a builder but then realized that BottomNavigationBarItem is not actually a widget ... 

So I am trying to make a decoder ... but since BottomNavigationBarItem.Icon is a widget I am not sure a decoder is the right thing either.

Is there a construct/approach that you think makes most sense for this case?

**Comment by aktxyz** [comment]
I am pretty sure this is not really the clean way to implement this ... but it seems to work even though it looks ugly!

I tried to follow the buildler model but it does not extend ```JsonWidgetBuilder``` so it's clearly not a normal builder.

 Instead of implementing a ```BuildCustom``` method that returns a widget, it implements a ```Build``` method that returns a ```BottomNavigationBarItem```.

```
class JsonBottomNavigationBarItemBuilder {
  JsonBottomNavigationBarItemBuilder({
    this.activeIcon,
    this.backgroundColor,
    this.icon,
    this.label,
    this.tooltip,
  });

  final JsonWidgetData? activeIcon;
  final Color? backgroundColor;
  final JsonWidgetData? icon;
  final String? label;
  final String? tooltip;

  static JsonBottomNavigationBarItemBuilder? fromDynamic(
    dynamic map, {
    JsonWidgetRegistry? registry,
  }) {
    JsonBottomNavigationBarItemBuilder? result;

    if (map != null) {
      result = JsonBottomNavigationBarItemBuilder(
        activeIcon: JsonWidgetData.fromDynamic (map['activeIcon']),
        backgroundColor: ThemeDecoder.decodeColor (map['backgroundColor']),
        icon: JsonWidgetData.fromDynamic (map['icon']),
        label: (map['label']?.toString()),
        tooltip: (map['tooltip']?.toString()),
      );
    }

    return result;
  }

  BottomNavigationBarItem build({
    ChildWidgetBuilder? childBuilder,
    required BuildContext context,
    Key? key,
  }) {
    return BottomNavigationBarItem(
      icon: icon!.build(childBuilder: childBuilder, context: context),
      label: label,
    );
  }
}
```

**Comment by crisperit** [comment]
Hello - maybe try to create a PR for that and let's discuss the implementation on PR level
