### ISSUE TITLE
infinite scroll ... any advice?

### ISSUE THREAD

**Issue by aktxyz** [peiffer-innovations/json_dynamic_widget#145]
I need to implement and "infinite scroll".

Basically I load a page with a list view that has 20 items ... and would like to load 20 more when I scroll to the list end.

The part I am stuck on is the best way to append the new items to the listview ... any thoughts?

**Comment by crisperit** [comment]
The idea might be to create a builder for 
https://pub.dev/packages/infinite_scroll_pagination

**Comment by jpeiffer** [comment]
Closing as there really isn't much more that can be done from my end and this isn't actually an issue.  This would be better as a stackoverflow.com question.
