### ISSUE TITLE
is it possible to reuse parts of json?

### ISSUE THREAD

**Issue by bonsoirelliot** [peiffer-innovations/json_dynamic_widget#161]
Hello! Is there any way to implement something like this? is it possible to reuse parts of json?
![image](https://user-images.githubusercontent.com/27853419/232436419-b07ee938-2384-48fe-9dfe-6d3b96c77e89.png)

**Comment by crisperit** [comment]
Hello - I think that you can save the widgets in variables via `set_widget` and render it from variable like that:
https://github.com/peiffer-innovations/json_dynamic_widget/blob/main/example/assets/pages/issue_20_single.json

I thought to create the plugin called `component`.  In mine idea for that plugin there will be a possibility to define a group of builders together with a possibility to pass the input args.  But these are only the plans for now : D

**Comment by jpeiffer** [comment]
What @crisperit said is correct.  That is a built in way.  Another would be to create your own builder that can read the reusable JSON from somewhere and just render it.
