### ISSUE TITLE
Is it possible to add business logic dynamically?

### ISSUE THREAD

**Issue by MeiChao** [peiffer-innovations/json_dynamic_widget#164]
For example, there is a dynamic form that is based on some form styles, validation rules, etc. that are issued by an API interface. The API interface also supports some logical validation.

**Comment by crisperit** [comment]
For sure you can have the view which renders different parts whenever some conditions (variable values) are fulfilled
 
https://github.com/peiffer-innovations/json_dynamic_widget/blob/main/example/assets/pages/conditional.json
https://github.com/peiffer-innovations/json_dynamic_widget/blob/main/lib/src/builders/json_conditional_builder.dart

So your api can change the variable values which can be used to render correct form parts etc..

You can also use the `expressions` engine
https://github.com/appsup-dart/expressions

To write things like:
```
"args": {
   "text": "${success ? 'Everything is okay!' : 'Whoops :<'  }"
}
```

**Comment by mtellect** [comment]
Nice plugin concept. What are your thoughts on the following:
1.) Dynamic routing. Supposing you want to present a new view to the user?
2.) Dynamic methods/functions. Supposing you fix a function remotely?

**Comment by crisperit** [comment]
Well what I've written isn't the concept but sth that works out of the box currently :D 

1.) Views can be stored in the variables and returned from some API
2.) When it comes to that I'm currently working on JS plugin which will make it possible to execute JS snippets 
```${js('new Date().toString()')}```
With such a flexible solution you might be able to use some API to for example to return JS validation functions that might be saved & rendered from some variable
