### ISSUE TITLE
ValueChanged<bool?>? 

### ISSUE THREAD

**Issue by narongchaiyakul** [peiffer-innovations/json_dynamic_widget#176]
pls sample json & func use "onDrawerChanged" 
don;'t clear interface ,
thank.

**Comment by crisperit** [comment]
@narongchaiyakul 
I've added the example of how to use such the `ValueChanged<bool?>`

@jpeiffer 
It is true that out of the box the values like that are not really supported. Maybe we shall provide some set of funcs like:
`setBooleanValue('booleanVarName')` => `ValueChanged<bool?>`
`setStringValue('stringVarName')` => `ValueChanged<string?>`
`setDynamicValue('dynamicVarName')` => `ValueChanged<dynamic?>`
...
