### ISSUE TITLE
json_dynamic_widget Is there any major difference from the technology described in the picture below?

### ISSUE THREAD

**Issue by Alvazz** [peiffer-innovations/json_dynamic_widget#18]
here :

![2dae09a9a27dc9198828bc63e88fd65088608](https://user-images.githubusercontent.com/50744096/98087176-b0916100-1eba-11eb-95a5-401b88d44f6c.png)

**Comment by Alvazz** [comment]
![95f243a1da7dafacffd72732dd758723267968](https://user-images.githubusercontent.com/50744096/98087523-2e556c80-1ebb-11eb-9e18-0d6103cc0baf.png)

**Comment by jpeiffer** [comment]
Yes.  There's no CI/CD compilation involved at all with this package.
