### ISSUE TITLE
Is it possible to use `shrinkWrap` property with dynamic `ListView`?

### ISSUE THREAD

**Issue by gredajustyna** [peiffer-innovations/json_dynamic_widget#180]
Hello,
I am trying to modify your example of dynamic ListView so that the add button is always right below the list, no matter the number of elements in the list. To reach that, I need to use the `shrinkWrap` property of the ListView. However, when the ListView is used as a `builderType` of dynamic widget, I see no option to specify additional args, like the `shrinkWrap` property. So, is there a way to specify `builderType` widget args when using dynamic widget?

**Comment by crisperit** [comment]
Hello - here is mine recent response for your issue.  Basically anything outside of `dynamic` will be placed as the args of `builderType` widget
https://github.com/peiffer-innovations/json_dynamic_widget/issues/116#issuecomment-1357896503

**Comment by gredajustyna** [comment]
This resolves my issue, thank you very much!
