### ISSUE TITLE
example multiFunction Call

### ISSUE THREAD

**Issue by narongchaiyakul** [peiffer-innovations/json_dynamic_widget#192]
pls. example code.
"onPressed": "${callMultiFunctions(set_value('xx','1234'),simplePrintMessage('test '))}"

**Comment by jpeiffer** [comment]
For things that don't care about the answer, you could probably do it using an array.

```
"onPressed": "${[set_value('xx','1234'),simplePrintMessage('test ')]}"
```

That's not really supported / how the expressions are intended to be used so YMMV.
