### ISSUE TITLE
ListView.builder

### ISSUE THREAD

**Issue by naveen715** [peiffer-innovations/json_dynamic_widget#197]
How can i implement a ListView.builder where i am getting the data to be displayed inside the listview as a json file .

**Comment by piyushdevganiya** [comment]
here is example of **ListView.builder**
{
"type": "set_value",
"args": {
"entries": {
"data": [
{
"title": "ABC",
"subtitle": "XYZ"
}
]
},
"template": {
"type": "container",
"args": {
"padding": 20
},
"child": {
"type": "list_tile",
"args": {
"subtitle": {
"type": "text",
"args": {
"text": "${value['subtitle']}"
}
},
"title": {
"type": "text",
"args": {
"text": "${value['title']}"
}
}
}
}
}
},
"child": {
"type": "scaffold",
"args": {
"appBar": {
"type": "app_bar",
"args": {
"title": {
"type": "text",
"args": {
"text": "List View"
}
}
}
},
"body": {
"type": "list_view",
"children": "${for_each(entries['data'], 'template')}"
}
}
}
}

**Comment by naveen715** [comment]
> here is example of **ListView.builder**
> 
> ```
> {
> "type": "set_value",
> "args": {
> "entries": {
> "data": [
> {
> "title": "ABC",
> "subtitle": "XYZ"
> }
> ]
> },
> "template": {
> "type": "container",
> "args": {
> "padding": 20
> },
> "child": {
> "type": "list_tile",
> "args": {
> "subtitle": {
> "type": "text",
> "args": {
> "text": "${value['subtitle']}"
> }
> },
> "title": {
> "type": "text",
> "args": {
> "text": "${value['title']}"
> }
> }
> }
> }
> }
> },
> "child": {
> "type": "scaffold",
> "args": {
> "appBar": {
> "type": "app_bar",
> "args": {
> "title": {
> "type": "text",
> "args": {
> "text": "List View"
> }
> }
> }
> },
> "body": {
> "type": "list_view",
> "children": "${for_each(entries['data'], 'template')}"
> }
> }
> }
> }
> ```

Thank you for replying this really helped . Is it possible that template and set value are in different json files and i can import them as variable in the json file

**Comment by naveen715** [comment]
> {
> "type": "set_value",
> "args": {
> "entries": {
> "data": [
> {
> "title": "ABC",
> "subtitle": "XYZ"
> }
> ]
> },
> "template": {
> "type": "container",
> "args": {
> "padding": 20
> },
> "child": {
> "type": "list_tile",
> "args": {
> "subtitle": {
> "type": "text",
> "args": {
> "text": "${value['subtitle']}"
> }
> },
> "title": {
> "type": "text",
> "args": {
> "text": "${value['title']}"
> }
> }
> }
> }
> }
> },
> "child": {
> "type": "scaffold",
> "args": {
> "appBar": {
> "type": "app_bar",
> "args": {
> "title": {
> "type": "text",
> "args": {
> "text": "List View"
> }
> }
> }
> },
> "body": {
> "type": "list_view",
> "children": "${for_each(entries['data'], 'template')}"
> }
> }
> }
> }

this is not working in case of newer versions of the library do you have any examples in version 7.0.1
