### ISSUE TITLE
Integrate date picker and time picker as a custom widget

### ISSUE THREAD

**Issue by satheesh-agnext** [peiffer-innovations/json_dynamic_widget#199]
How to integrate date picker and time picker as a custom widget? Is there any sample available for the same ?

**Comment by RKDEVSYS** [comment]
??

**Comment by crisperit** [comment]
There is no such the example but it should be done similar to `show_dialog`

You have to create the custom function which will call
https://api.flutter.dev/flutter/material/showDatePicker.html

The only challenge is to pass build context - but it can be done via `save_context` builder
https://github.com/peiffer-innovations/json_dynamic_widget/blob/main/example/assets/pages/dynamic.json#L26-L29


If you'll create something nice then you are welcome to commit it :D
