### ISSUE TITLE
run function on button click

### ISSUE THREAD

**Issue by Ahmedmedhat187** [peiffer-innovations/json_dynamic_widget#2]
Hello,

How can I run function on button click,

and on Form page how to catch the data that user entered on variables and print it

**Comment by jpeiffer** [comment]
Functions must be registered with the `JsonWidgetRegistry` and are referenced by surrounding the text with `##` on both sides.

You can see an example of this in action inside of the https://github.com/peiffer-innovations/json_dynamic_widget/blob/main/example/assets/pages/conditional.json file.  In that example, it will change the value displayed based on the button that has been clicked.

Additionally the https://github.com/peiffer-innovations/json_dynamic_widget/blob/main/example/assets/pages/form.json example gives an example of a form with validation.

I'd be happy to post an example closer to what you're looking for if you can provide me more details of what the screen you'd like to see looks like as well as an example of the output you'd like to see from it.

**Comment by Ahmedmedhat187** [comment]
Hello jpeiffer,

Thanks for helping me :)

I want to make post request to send data to server after submitting form

**Comment by jpeiffer** [comment]
Assuming you stick to the built in widgets, here's a high level...

1. Give an ID to each input element
2. Whenever the input value changes the `JsonWidgetRegistry` will get a `value` set on it with the ID as the key.  You can get these values using the `getValue(String)` function.
3. You likely need to register a custom function.  Let's call it "submitForm".  On the `JsonWidgetRegistry`.  It'll probably look something like...
  ```dart
  var registry = JsonWidgetRegistry.instance;  
  registry.registerFunction('submitForm', (args, registry) {
    // get all the values then post them to the server
  });
  ```
4. If your values are fully dynamic then you might want to give the form some name.  Then you can prefix all the ids with that name.  That may look like...
  ```dart
  var registry = JsonWidgetRegistry.instance;  
  registry.registerFunction('submitForm', (args, registry) {
    var values = registry.values;
    var formValues = {};
    values.forEach((key, value) => if (key.startsWith('$myFormId_') formValues[key] = value);

    http.post(body: formValues, url: myUrl);
  });
  ```
5. The last thing you need is to wire up the function call.  Then you will probably need some sort of a button.
  ```json
  {
    "type": "flat_button",
    "args": {
      "onPressed": "##submitForm()##"
    }
  }
  ```

If you need to perform validation, take a look at the example app and the [form.json](https://github.com/peiffer-innovations/json_dynamic_widget/blob/main/example/assets/pages/form.json) example asset.  That provides code for performing form validation.

**Comment by jpeiffer** [comment]
Please let me know if you need anything else or if you think this issue should be closed.
