### ISSUE TITLE
Problem setting state

### ISSUE THREAD

**Issue by RKDEVSYS** [peiffer-innovations/json_dynamic_widget#200]
**I used a text_form_field and a simple text and defined the variable that was in the id of the text_form_field in the text widget, when typing anything in the text_form_field widget the text widget is only updated once, that is, if I change any value in the text_form_field it will only be changed once in text_form_field, could you help me with this situation?**

![Captura de tela de 2023-08-27 06-54-42](https://github.com/peiffer-innovations/json_dynamic_widget/assets/33296132/78cca5df-ba78-40c0-abfb-0501f5f7db7c)

**Comment by RKDEVSYS** [comment]
The problem only occurs when "initialValue" is set

**Comment by jpeiffer** [comment]
Please provide a full example of the issue.  Absent that, there isn't much I can / will do.

**Comment by crisperit** [comment]
Just to note - you are using deprecated way of passing vars
https://github.com/peiffer-innovations/json_dynamic_widget#migration-to-4xx-version
