### ISSUE TITLE
supported widgets

### ISSUE THREAD

**Issue by MahdiPishguy** [peiffer-innovations/json_dynamic_widget#21]
which widgets supported by this library?

**Comment by jpeiffer** [comment]
The ones that come built in are listed in the README here:
https://github.com/peiffer-innovations/json_dynamic_widget#built-in-widgets

However, you can add your own support for custom widgets, even standard Flutter ones that the library doesn't have built in support as well by following the guide:
https://github.com/peiffer-innovations/json_dynamic_widget#creating-custom-widgets
