### ISSUE TITLE
How to create validator to check the length of entered input

### ISSUE THREAD

**Issue by naveen715** [peiffer-innovations/json_dynamic_widget#210]
I am performing a text form field validator using "validators": [
                                      {
                                        "type": "required"
                                      }
                                    ] 
how can i modify it to validate the length of a string

**Comment by jpeiffer** [comment]
The validation relies on [this package](https://github.com/peiffer-innovations/form_validation) that should have the documentation you need.  If you have further concerns feel free to re-open the issue.
