### ISSUE TITLE
I'm facing problems while running version 7.0.0+2 example.

### ISSUE THREAD

**Issue by vpsdeveloper** [peiffer-innovations/json_dynamic_widget#214]
When trying to run the example, I encountered errors like:

- **Target of URI hasn't been generated: 'package:example/src/components/example_registrar.g.dart'.**
- **Target of URI hasn't been generated: 'package:example/src/dotted_border_builder.g.dart'.**
- **Target of URI hasn't been generated: 'package:example/src/svg_builder.g.dart'.**

After commenting out the problematic code blocks, I encountered a different error. 

![image](https://github.com/peiffer-innovations/json_dynamic_widget/assets/97819400/cb2205d4-7e78-47f4-baa9-8854cd9a7b27)

**Comment by crisperit** [comment]
@vpsdeveloper 
`strokeAlignCenter` was added 4 months ago to the Flutter so maybe some old version of Flutter you have and generated code is not valid for supported Flutter version

@jpeiffer What version of Flutter is needed to have in order to validly built that project

I have Flutter (Channel stable, 3.13.3) and also some issues with generation

```
ERROR: ../lib/src/builders/json_floating_action_button_builder.g.dart:104:26: Error: Couldn't find constructor '_DefaultHeroTag'.
json_floating_action_button_builder.g.dart:104
ERROR:     this.heroTag = const _DefaultHeroTag(),
ERROR:                          ^^^^^^^^^^^^^^^
ERROR: ../lib/src/builders/json_floating_action_button_builder.g.dart:416:26: Error: Couldn't find constructor '_DefaultHeroTag'.
json_floating_action_button_builder.g.dart:416
ERROR:     this.heroTag = const _DefaultHeroTag(),
ERROR:                          ^^^^^^^^^^^^^^^
ERROR: lib/src/export_example_page.dart:56:30: Error: Too many positional arguments: 0 allowed, but 1 found.
export_example_page.dart:56
ERROR: Try removing the extra positional arguments.

ERROR:               title: JsonText('Example'),
ERROR:                              ^
```

For example it is constructing the code from internal value as the default - and because of that the generated file is invalid

**Comment by jpeiffer** [comment]
The generator runs via Flutter 3.13.  If you need the generated files in addition to the source, you can download them from pub.dev [here](https://pub.dev/packages/json_dynamic_widget/versions).

If you need to compare, you can use that to compare to what you're seeing locally.  The published generated files from from the `stable` branch at build time using a Linux build agent.

**Comment by crisperit** [comment]
@jpeiffer Isn't it a bug that generator tries to use `_DefaultHeroTag` private field as default value?

**Comment by jpeiffer** [comment]
Oh, this is on JSON generation from Dart and not generating the Dart code itself?  If so, can you provide the full Dart code you are trying and I can try it out?

**Comment by crisperit** [comment]
Ok after upgrading mine code and the Flutter everything is building fine - so issues solved for me :)

**Comment by jpeiffer** [comment]
I'm going to assume this can be closed.  If the issue persists, feel free to re-open or create a new one with additional details.
