### ISSUE TITLE
JsonArgEncoder + JsonArgAlias issue

### ISSUE THREAD

**Issue by Maatteogekko** [peiffer-innovations/json_dynamic_widget#219]
```dart
class ExampleData {}

class Example extends StatelessWidget {
  Example(this.data);

  final ExampleData data;

  Widget build(BuildContext context) {
    return SizedBox();
  }
}

@jsonWidget
abstract class _JsonExampleBuilder extends JsonWidgetBuilder {
  const _JsonExampleBuilder({
    required super.args,
  });

  @JsonArgEncoder('name')
  static String _encodeName(ExampleData value) {
   // ...
  }

  @JsonArgDecoder('name')
  ExampleData _decodeName({
    required dynamic value,
  }) {
    // ...
  }

  @JsonArgSchema('name')
  static Map<String, dynamic> _nameSchema() {
    return SchemaHelper.stringSchema;
  }

  @JsonPositionedParam('data')
  @JsonArgAlias(alias: 'name', name: 'data')
  @override
  Example buildCustom({
    ChildWidgetBuilder? childBuilder,
    required BuildContext context,
    required JsonWidgetData data,
    Key? key,
  });
}
```

With this code, the generator generates invalid code in `JsonExampleBuilderModel.toJson`:
```dart
final nameEncoded = _JsonSvgIconBuilder._encodeName(name);
```

It should be 
```dart
final nameEncoded = _JsonSvgIconBuilder._encodeName(data);
```

or `JsonExampleBuilderModel.data` should have been `JsonExampleBuilderModel.name`.

Or am I missing some configuaration/annotation?

PS:
Amazing package! And with code generation it's become even more amazing. Keep it up! 🚀

**Comment by jpeiffer** [comment]
Is it possible to create a runnable example of the issue?  I kind of understand the gist of the example code, but to be completely honest, I am not going to spend the time to take the generalized example and try to create a real reproduction of the problem.

What I will do is take a real example, run it, and try to find out what's going wrong.

**Comment by Maatteogekko** [comment]
@jpeiffer did you look at the PR?

**Comment by crisperit** [comment]
@jpeiffer I guess it shouldn't be merged as now the `example` is not able to be built :D

**Comment by jpeiffer** [comment]
I did merge it and things seem working (at least "on my computer") with the latest of everything.  Is this still an issue after the latest versions?

**Comment by Maatteogekko** [comment]
I cloned the main branch again to make sure that I didn't have some stale dependency, but the issue remains :(

**Comment by Maatteogekko** [comment]
Changing
https://github.com/peiffer-innovations/json_dynamic_widget/blob/9b494350a696ce65118e03ea464bcf5d3a9e787a/codegen/lib/src/builder/json_widget_library_builder.dart#L742C1-L742C1
to
`final ${name}Encoded = ${element.name}.${encoder.name}(${param.name});`
fixes it for me. I don't know if it breaks something else though..

**Comment by jpeiffer** [comment]
Fixed with the code generator version `1.0.3+2`.  Please let me know if you are still having this problem.

**Comment by Maatteogekko** [comment]
It works now! Thanks @jpeiffer for your time and effort

**Comment by Maatteogekko** [comment]
I just noticed a problem related to the patch that fixed this issue.

The `toJson` is invalid since the key for the aliased parameter does not use the correct name.
 https://github.com/peiffer-innovations/json_dynamic_widget/blob/e8df6088dbd5341a2410660d69eb6489d0944bc6/codegen/lib/src/builder/json_widget_library_builder.dart#L752

Should be instead:
`'${name}': ${defaultValueCode == null ? '' : '$defaultValueCode == $name ? null : '}${name}Encoded,`

**Comment by crisperit** [comment]
@Maatteogekko Can you create the PR with the fix?

**Comment by Maatteogekko** [comment]
sure. PR done, let me know if I can do anything else to help.
