### ISSUE TITLE
Add encoders to default json builders

### ISSUE THREAD

**Issue by Maatteogekko** [peiffer-innovations/json_dynamic_widget#220]
I was really surprised when I tried to reverse encode the following and it returned a json with `null` as the decoration.
```dart
JsonContainer(
  padding: const EdgeInsets.all(9),
  decoration: const BoxDecoration(
    shape: BoxShape.circle,
    gradient: LinearGradient(
      colors: [
        Color(0xFFf7b928),
        Color(0xFFd88515),
      ],
      begin: Alignment.topLeft,
      end: Alignment.bottomRight,
    ),
  ),
  foregroundDecoration: null,
)
```

I had to do the following:
```dart
JsonContainer(
  padding: const EdgeInsets.all(9),
  decoration: {
    'shape': 'circle',
    'gradient': {
      'type': 'linear',
      'begin': 'topLeft',
      'end': 'bottomRight',
      'colors': ['f7b928', 'd88515'],
    }
  },
  foregroundDecoration: null,
)
```

I found out that the JsonContainerBuilder is missing the encoders for the decorations, like:
```dart
@JsonArgEncoder('decoration')
  static String _encodeDecoration(BoxDecoration value) {
    return ThemeEncoder.encodeBoxDecoration(
        value,
      );
  }
```

Is this why the first code sample does not generate the decoration? Can it be added?  
The first example is much more pleasant and intuitive to write.

**Comment by jpeiffer** [comment]
You are absolutely correct in your analysis.  I simply forgot to put the custom encoder to match the custom decoder and that was the root of the problem.  This is fixed with `7.0.2`.
