### ISSUE TITLE
 Issue with Always Receiving Null value in validateForm Function

### ISSUE THREAD

**Issue by piyushdevganiya** [peiffer-innovations/json_dynamic_widget#229]
I am experiencing an issue where the **validateForm** function consistently receives null values for its arguments, despite passing custom arguments.
Here's the code where this problem occurs:
`{
  "type": "expanded",
  "args": {
    "child": {
      "type": "elevated_button",
      "args": {
        "onPressed": "${validateForm('form_context','URL',{'user_name':'user_name','password':'password'},{'token':'123'})}",
        "style": {
          "backgroundColor": "ff2D84D3"
        },
        "child": {
          "type": "padding",
          "args": {
            "padding": [
              10,
              15,
              10,
              15
            ],
            "child": {
              "type": "save_context",
              "args": {
                "key": "form_context",
                "child": {
                  "type": "text",
                  "args": {
                    "text": "Login",
                    "style": {
                      "fontSize": 18,
                      "color": "FFE2E5DE"
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  }
}`
**validateForm** function code
`'validateForm': ({args, required registry}) => () async {
          final BuildContext context = registry.getValue(args![0]);
          final valid = Form.of(context).validate();
          var data = {};
          args[2].forEach((key, value) {
            data[key] = registry.values[value];
          });
          if (args!.length > 3) {
            args[3].forEach((key, value) {
              data[key] = registry.values[value];
            });
          }
          print(data);
          registry.setValue('form_validation', valid);
        }`
**output is getting now**
{user_name: hh, password: hh, token: null}
**Expected output**
 {user_name: hh, password: hh, token: '123'}

**Comment by jpeiffer** [comment]
If you can create a PR to the example app showing the problem and describing the expected outcome I will try to help.  Otherwise, this is a better question for stackoverflow.com and not likely something I'll invest time in.

**Comment by crisperit** [comment]
Isn't it the same as in here? So you need to add `"listen":["token"]` in order to re-render the calling function?

https://github.com/peiffer-innovations/json_dynamic_widget/issues/257

**Comment by crisperit** [comment]
No movement in here - closing. Please reopen with some example page on separate branch
