### ISSUE TITLE
How to use Drawer and bottomNavigationBar in JSON

### ISSUE THREAD

**Issue by piyushdevganiya** [peiffer-innovations/json_dynamic_widget#230]
I'm currently working on a project where I need to implement a Drawer and a bottom navigation bar using JSON for configuration. I'm facing some challenges and could use some guidance on how to achieve this.

**Comment by jpeiffer** [comment]
This isn't an issue with the framework and a better question for stackoverflow.com.

**Comment by Stiofan** [comment]
@piyushdevganiya did you ever solve this?
