### ISSUE TITLE
eval("${xxxx}");

### ISSUE THREAD

**Issue by idrlab1234** [peiffer-innovations/json_dynamic_widget#233]
i can do function  like javascript eval()

**Comment by crisperit** [comment]
Yeah - there is a plugin https://github.com/peiffer-innovations/json_dynamic_widget_plugin_js along with the example https://github.com/peiffer-innovations/json_dynamic_widget_plugin_js/blob/main/example/assets/pages/js.json

I see that it is missing from README so readding it

**Comment by idrlab1234** [comment]
"onClicked": "${1+2}",
i want to call Expression Function  like that ->.  registery.execute("${1+2}")
