### ISSUE TITLE
JsonWidgetData.fromDynamicList not passing registry argument to maybeFromDynamicList

### ISSUE THREAD

**Issue by PaulFrederikson** [peiffer-innovations/json_dynamic_widget#243]
In the major rewrite of the **JsonWidgetData** class for version 7, new static methods were added to generate JsonWidgetData objects from a dynamic List namely **fromDynamicList** and **maybeFromDynamicList**. Both methods take a (dynamic) list and optional (JsonWidgetRegistry) registry as arguments.

**fromDynamicList** calls **maybeFromDynamicList** but does not pass the registry argument, so if you call **fromDynamicList** with an alternative registry instance **maybeFromDynamicList** will just use the default registry instance.

```
  static List<JsonWidgetData> fromDynamicList(
    dynamic list, {
    JsonWidgetRegistry? registry,
  }) {
    final result = maybeFromDynamicList(list);
    if (result == null) {
      throw Exception(
        '[JsonWidgetData]: requested to parse from dynamic list, but the input is null.',
      );
    }

    return result;
  }
```
should be:
```
static List<JsonWidgetData> fromDynamicList(
    dynamic list, {
    JsonWidgetRegistry? registry,
  }) {
    final result = maybeFromDynamicList(list, registry: registry);
    if (result == null) {
      throw Exception(
        '[JsonWidgetData]: requested to parse from dynamic list, but the input is null.',
      );
    }

    return result;
  }
```

**Comment by jpeiffer** [comment]
Thanks for the detailed report!  Fixed tonight with 7.0.6
