### ISSUE TITLE
Components plugin

### ISSUE THREAD

**Issue by crisperit** [peiffer-innovations/json_dynamic_widget#247]
**Idea**

https://github.com/peiffer-innovations/json_dynamic_widget_plugin_components

Plugin which allows to define group of JSON widgets and expose one common interface to it. These groups of widgets are called components and they can be loaded from the file or URL.

They can be reused across multiple of views, reused, versioned and parameterized..

It will allow to create own design system, components library

**Why?**
Let's say we have multiple of JSON views and we have something common and always the same - for e.g. the header. 

Currently, we need to manually define the same group of JSON widgets that are building the header on each of the view. It is breaking DRY rule and is much harder to maintain (for example if the each view is maintained by different team..

The idea is to define common set of components that can be reused by each view (+ it will make json definition much more smaller in the size as the components might be built in as assets and shared by the library)

**Example usage**

**Table of Contents**

- [json_dynamic_widget_plugin_components](#json_dynamic_widget_plugin_components)
  - [Table of Contents](#table-of-contents)
  - [Live Example](#live-example)
  - [Introduction](#introduction)
  - [Using the Plugin](#using-the-plugin)

# json_dynamic_widget_plugin_components

## Table of Contents

* [Live Example](#live-example)
* [Introduction](#introduction)
* [Using the Plugin](#using-the-plugin)

## Live Example

* [Web](https://peiffer-innovations.github.io/json_dynamic_widget_plugin_components/web/index.html#/)

## Introduction

Plugin to the [JSON Dynamic Widget](https://peiffer-innovations.github.io/json_dynamic_widget) which allows to combine  the set of JSON widgets into one and define 
own interface.

## Using the Plugin

1. Bind the plugin.

```dart
import 'package:json_dynamic_widget/json_dynamic_widget.dart';
import 'package:json_dynamic_widget_plugin_components/json_dynamic_widget_plugin_components.dart';


void main() {
  // Ensure Flutter's binding is complete
  WidgetsFlutterBinding.ensureInitialized();

  // ...

  // Get an instance of the registry
  var registry = JsonWidgetRegistry.instance;

  // create valid component loader
  var basePath = 'assets/components'
  final loader = AssetComponentLoader(basePath);
  
  // Bind the plugin to the registry. This is necessary for the registry to
  // find the widget provided by the plugin
  JsonComponentsPlugin.bind(registry, loader);

  // ...
}

```

2. Create the JSON file with component data and place it in `{components_path}/{component_name}/{version}.json`.

```
// {components_path}/centered_text/1.0.0.json
{
    "name": "centered_text",
    "version": "1.0.0",
    "params": [
        {
            "name": "text",
            "description": "The centered text value.",
            "defaultValue": ""
        }
    ],
    "content": {
        "type": "center",
        "args": {
            "child": {
                "type": "text",
                "args": {
                    "text": "{text}"
                }
            }
        }
    }
}
```

3. Use the component in the `json_dynamic_widget`.

```
"type": "component",
"args": {
    "name": "centered_text",
    "version": "1.0.0",
    "args": {
      "text": "Some centered text"
    }
}
```

**Questions**
Feel free to ask any questions and share your ideas regarding it :D

**Comment by jpeiffer** [comment]
I would recommend going with a "loader" pattern rather than a `basePath`.  Something like:

```dart
abstract class ComponentLoader {
  const ComponentLoader({
    required this.id,
  });
  
  Future<List<Component>> loadComponents();
}

class AssetComponentLoader extends ComponentLoader {
  //...
}

class NetworkComponentLoader extends ComponentLoader {
  // ...
}
```

... then have...

```dart
final loader = AssetComponentLoader(basePath);

JsonComponentsPlugin.bind(registry, loader);
```

This way components could be assets from the app, loaded via a network, loaded via a database, etc.

**Comment by jpeiffer** [comment]
Next, and this is being nitpicky so feel free to ignore it, I would recommend changing:

```json
// {components_path}/centered_text/1.0.0.json
{
    "name": "centered_text",
    "version": "1.0.0",
    "args": [
        {
            "name": "text",
            "description": "The centered text value.",
            "defaultValue": ""
        }
    ],
    "data": {
        "type": "center",
        "args": {
            "child": {
                "type": "text",
                "args": {
                    "text": "{text}"
                }
            }
        }
    }
}
```

... to...

```json
// {components_path}/centered_text/1.0.0.json
{
    "name": "centered_text",
    "version": "1.0.0",
    "params": [
        {
            "name": "text",
            "description": "The centered text value.",
            "defaultValue": ""
        }
    ],
    "content": {
        "type": "center",
        "args": {
            "child": {
                "type": "text",
                "args": {
                    "text": "{text}"
                }
            }
        }
    }
}
```

The term `args` already has meaning within this package, and you're using a very different meaning so to prevent confusion I think we should use a different word.  I picked `params` above, but I equally like `with` which follows the standards from GH Actions too.  And `data` has too many different possible meanings so I would recommend `content` since that's really what it represents.  It's the content of the component.

**Comment by crisperit** [comment]
@jpeiffer Really thanks for your insight - I agree with these modifications and I'll put these into a feature spec

**Comment by crisperit** [comment]
During the design process I've came into some issues:
- What if someone will use multiple of components in which every of them has for example text input which overrides "textInput" value and we want it to be unique across multiple of components?
- What if specific component want to use specific `variable` that was defined in a scope of the component?
- Should the components be rendered once?

So here's mine refreshed idea:

```
// {components_path}/centered_text/1.0.0.json
{
    "name": "centered_text",
    "version": "1.0.0",
    "variables": [
        {
            "name": "text",
            "description": "The centered text value.",
            "defaultValue": ""
        }
    ],
    "content": {
        "type": "center",
        "args": {
            "child": {
                "type": "text",
                "args": {
                    "text": "${text}"
                }
            }
        }
    }

// usage
"type": "component",
"args": {
    "id": "centeredText1",
    "name": "centered_text",
    "version": "1.0.0",
    "variables": {
      "text": "Some centered text"
    }
}
```

- Each component needs to define "id" field which will be used to add unique suffix to each of the component variables. By default the id can be generated as UUID if missing
e.g. `text => component_centeredText1_text``

- Each of the variables defined on component usage are loaded as prefixed variables and used as variables in a component. So that they json widgets parts can automatically be refreshed via a common mechanism

- Component will be rendered once, will be scoped by its id on registry level

- Any variable change on `usage` side will effect only in replacing the `variable` inside the component

- Only in case of `version` or `name` change we should consider to re-render the whole  component from a scratch

**Comment by crisperit** [comment]
Here is PR:
https://github.com/peiffer-innovations/json_dynamic_widget_plugin_components/pull/1

Here is updated spec:
https://github.com/peiffer-innovations/json_dynamic_widget_plugin_components/tree/init-version?tab=readme-ov-file#about

**Comment by crisperit** [comment]
PR to update docs, whole components plugin is done
https://github.com/peiffer-innovations/json_dynamic_widget/pull/293
