### ISSUE TITLE
Error Instance of _HandledJsonWidgetException

### ISSUE THREAD

**Issue by ARCHAMO** [peiffer-innovations/json_dynamic_widget#25]
Hi I am replicating the dynamic form example with the form.json file.
But when compiling it throws an error.
![image](https://user-images.githubusercontent.com/12633358/104766576-d2b82280-5738-11eb-9340-bd0704f75327.png)

If I remove the onPressed property of the button. Compile as follows.

![image](https://user-images.githubusercontent.com/12633358/104766843-3a6e6d80-5739-11eb-8a1f-77b3c863e3d6.png)
![image](https://user-images.githubusercontent.com/12633358/104766878-49552000-5739-11eb-9cf5-5118221e2dc9.png)
![image](https://user-images.githubusercontent.com/12633358/104766952-61c53a80-5739-11eb-9e41-9f0d412da6ba.png)

This is the code that I am using to call the Json from my Api and process it.
```
import 'dart:convert';

import 'package:flutter/material.dart';
import 'package:json_dynamic_widget/json_dynamic_widget.dart';
import 'package:http/http.dart' as http;

class SimpleText extends StatefulWidget {
  const SimpleText({Key key}) : super(key: key);
  final url = 'http://[IP_ADRESS]:[PORT]/api/widgets';

  @override
  _SimpleTextState createState() => _SimpleTextState();
}

class _SimpleTextState extends State<SimpleText> {
  @override
  Widget build(BuildContext context) {
    return FutureBuilder(
      builder: (context, AsyncSnapshot<http.Response> snapshot) {
        if (snapshot.hasData) {
          var widgetJson = json.decode(snapshot.data.body);
          var widget = JsonWidgetData.fromDynamic(
            widgetJson,
          );
          return widget.build(context: context);
        } else {
          return Scaffold(
            body: Center(
              child: CircularProgressIndicator(),
            ),
          );
        }
      },
      future: _getWidget(),
    );
  }

  Future<http.Response> _getWidget() async {
    return http.get(widget.url);
  }

  validateForm() {
    print('Formulario validado');
  }
}
```

**Comment by OgieBen** [comment]
Hi @ARCHAMO , after going through the docs it appears that you have to register your functions using the `registry.registerFunctions()` method otherwise your functions may not be loaded into memory.

**Comment by jpeiffer** [comment]
@OgieBen is correct (also, thanks for the comment!).

Custom functions must be registered via the registry before they can be used.  Otherwise, the registry has no way to identify the function which causes the error you are seeing.

In the example, you can see the registering of that function here:
https://github.com/peiffer-innovations/json_dynamic_widget/blob/main/example/lib/main.dart#L94
