### ISSUE TITLE
Whole App getting freeze when called build 2nd time on a registry. 

### ISSUE THREAD

**Issue by chetanApnaklub** [peiffer-innovations/json_dynamic_widget#251]
I had created a json which is using type list_view and I am using it with pagination so whenever new items arrive in response I added them in data of list_view and call build onto same registry instance through which initial list_view rendered. And whenever I call build again on same registry instance whole UI is getting freeze of App, even back button won't work. Only solutions remains for me is close app by pressing home button. 

I am not sure is it due to 'list_view' or not. To check this I had created another json using list_view, not so complex this time but it didn't freeze at all.

Even I had created my own type and their I am calling build multiple times on same registry and it freeze there as well, now their was no usage on list_view.

only solutions remains for me is to create registry object every time I want to call build.

**Comment by crisperit** [comment]
Can you create the new branch and the page with the issue in the example?

e.g. :
https://github.com/peiffer-innovations/json_dynamic_widget/blob/main/json_dynamic_widget/example/assets/pages/issue_30.json

**Comment by chetanApnaklub** [comment]
here it is, I had removed some of the function calls from json which were having custom definitions created by me and instead set the expected value in json to be returning from that function calls

**Comment by crisperit** [comment]
I do not see `list_view` in that example but rather `for_each` call

Hmm I guess this all and some other topics are suggesting us that we need to add some pretty straightforward pagination support @jpeiffer 

To fix that specific issue we need to have a proper and working example put into `example/pages/issue_251.json`
I'm not sure if calling manually `build` is ever the good idea : D
