### ISSUE TITLE
Unable to get text_form_field's value at submission of the form

### ISSUE THREAD

**Issue by 1abdurRehman** [peiffer-innovations/json_dynamic_widget#257]
**Describe the bug**
When i pass the variable to validateForm function at form.json, i am unable to get the values of the variable e.g email_address

**To Reproduce**
1. Go to json_dynamic_widget/example/assets/pages/form.json
2. At line 252, pass email_address as second param to validateForm function
3. At launcher.dart, add print statement to print the value of email_address
4. it prints null, however it should print the user inputed value

**Expected behavior**
text_form_field onChanged values should be accessibly on submission of form

**Example PR**
https://github.com/peiffer-innovations/json_dynamic_widget/pull/256

Flutter version:
Flutter 3.16.7
Tools • Dart 3.2.4 • DevTools 2.28.5

Thank you @jpeiffer @crisperit for your hard work on this package. While I've gone through the documentation, I'm encountering some difficulties at this stage. Any guidance or suggestions you could offer would be greatly appreciated!

**Comment by crisperit** [comment]
@1abdurRehman Hello!

Recently @jpeiffer has disabled all automatically added variable listeners. You need to add it manually via `listen` array in json to refresh the callable attached for submitButton

```
                                "type": "elevated_button",
                                "id": "submit_button",
                                "listen": ["email_address"],
 ```
 
 Let me know if that solves your issue :)

**Comment by 1abdurRehman** [comment]
@crisperit Thanks a lot!
your solution worked. I would like to share another approach which i have used i.e to get the value from registry at validateForm function

```
'validateForm': ({args, required registry}) => () {
      
      final BuildContext context = registry.getValue(args![0]);
      final valid = Form.of(context).validate();
      registry.setValue('form_validation', valid);
      if (valid) {
        final emailAddress = registry.getValue('email_address'); // id of text_form_field
        print(emailAddress);
     }
},
```
____________
One more issue related to text_form_field I am facing, borderSide property is not being applied, while the borderRadius property is being applied successfully. Thanks in advance
```
{
  "border": {
    "type": "outline",
    "gapPadding": 3,
    "borderSide": {
      "width": 5,
      "color": "#182546"
    },
    "borderRadius": {
      "type": "circular",
      "radius": 8
    }
  }
}
```
