### ISSUE TITLE
for_each with overwrited builders

### ISSUE THREAD

**Issue by Plaltair** [peiffer-innovations/json_dynamic_widget#258]
I have created a custom RichText and I have registered it inside the registry with the same "type" of the original (rich_text).
Inside the application it works fine, but when I use it inside the template of a loop, the template takes the default RichText builder. It doesn't work because my RichText is quite different from the original one.

I tested it with various custom builders; if I overwrite a default builder, that comes with the registry, with a custom builder with the same "type" and I use it inside for_each, the loop template takes the original one, not the overwriting builder.

I am using **JsonWidgetRegistry.instance** as registry.

**Comment by crisperit** [comment]
Please reopen with created example
