### ISSUE TITLE
running the example gives error: Type 'OverflowBoxFit' not found. 

### ISSUE THREAD

**Issue by hansbak** [peiffer-innovations/json_dynamic_widget#268]
after running the  
./generate_code.sh (i do not have pushd) but ran the build_runner both in the  json_dynamic_widget and  json_dynamic_widget/example directory

 i ran flutter run in the example directory I get:

./../../../.pub-cache/hosted/pub.dev/json_theme-6.4.1/lib/src/codec/theme_decoder.dart:9203:10: Error: Type 'OverflowBoxFit' not found.
  static OverflowBoxFit? decodeOverflowBoxFit(
         ^^^^^^^^^^^^^^
several times.

Regards,
Hans

**Comment by crisperit** [comment]
Hello @hansbak 
What's your Flutter version?
I think that at least Flutter v3.19 is needed based on latest commit https://github.com/peiffer-innovations/json_theme/commit/37eca8c85fe562ced0e98f900e61392a304f1a7a

**Comment by crisperit** [comment]
Now it's 3.22 - closing as no movement in here
