### ISSUE TITLE
Dynamic widget contribution

### ISSUE THREAD

**Issue by kperchlicki** [peiffer-innovations/json_dynamic_widget#28]
![dynamic](https://user-images.githubusercontent.com/17547300/120079272-66203d80-c0b3-11eb-8dbf-d28618ec8d8d.gif)

Hello - I really like your work and I've tried to create sth which will give a possibility to dynamically manage children of JsonWidgetData. 

I've managed to create `dynamic` type of builder which is giving a possibility to add / remove and modify children data. I also introduced `dynamic` function for triggering such an actions. 

By the way of implementing this dynamic builder type I've needed to create a way for building dialog.

If you are interested in mine contributions to this project regarding adding this `dynamic` builder or `show_dialog` function - lmk in this issue - I can provide you more mine implementations infos and / or create PR with that

**Comment by jpeiffer** [comment]
Interesting.  Sorry about the late reply, summers tend to get consumed by time with my kids.

I'd love to see a PR for this.

**Comment by kperchlicki** [comment]
Yeah do not worry. So maybe I'll first present the details of how this is work so maybe you can give some feedback regarding the functionalities. 

## Dynamic - description of how it works for now
So dynamic is a way which allows to dynamically generate children for specific json widget

### How to dynamically add item?
1. Define `dynamic` type of object in json file
```
{
  "type":"dynamic",
  "id":"items",
  "args":{
    "dynamic":{
      "builderType":"list_view",
      "childTemplate":{
          "id":"{id}",
          "type":"list_tile",
          "args":{
            "trailing":{
              "type":"icon_button",
              "args":{
                "icon":{
                  "type":"icon",
                  "args":{
                    "icon":{
                      "codePoint":59109,
                      "fontFamily":"MaterialIcons",
                      "size":50
                    }
                  }
                }
              }
            },
            "title":{
              "type":"text",
              "args":{
                "text":"{message}"
              }
            }
          }
        }
      },
      "initState":[
         {"id":"1","message":"First"},
         {"id":"2","message":"Second"}
      ]
   }
}
```

This part of json is defining in reality the `list_view` object with a "recipe" how to create `list_tile` children
But let's go through all properties:

* ` "type":"dynamic"` - name of the type
* `"args"` - the args are in reality `list_view` one (at the stage of the widget buld the dynamic key is deleted at the args are passed to `list_view builder`)
* `args.dynamic.builderType` - builder type of the parent
* `args.dynamic.childTemplate` - defines the template of the child. It is just a normal `JsonWidgetData` definition with the addition of params. In this example the params are `{id}`  - which is always generated for any dynamic child and `{message}` - which is a custom one. 
* `args.dynamic.initState` - contains the initial state of params which are used to built children. `JsonDynamicBuilder` puts this state to the registry under ` "id":"items",` id key. Whenever this state is changed the component is able to catch that and rebuild the children

2. Above example is generating `list_view` with 2 `list_tile` children (each of them has always a unique `id`). So now we have to define a way to trigger such an auction. And this is done via `dynamic` function which we have to define
```
{
  "type":"flexible",
  "child":{
    "type":"text_form_field",
    "id":"form_message",
    "args":{
      "decoration":{
        "hintText":"Write a message",
        "labelText":"Message"
      },
      "validators":[
        {
          "type":"required"
        }
      ]
    }
  }
}
...
{
  "type":"set_value",
  "args":{
    "dynamicItemsAdd":{
      "type":"add",
      "template":"items",
      "target":{
        "index":-1
      },
      "values":{
        "message":"{{form_message}}"
      }
    }
  },
  "child":{
    "type":"raised_button",
    "args":{
      "color":"#4a95ec",
      "colorBrightness":"dark",
      "onPressed":"##dynamic(dynamicItemsAdd)##"
    },
    "child":{
      "type":"container",
      "args":{
        "alignment":"center",
        "width":"infinity"
      },
      "child":{
        "type":"text",
        "args":{
          "text":"Add message"
        }
      }
    }
  }
}
```
1. Firstly I've added some form and the `text_form_field` which is constantly updating `form_message` variable
2. We have to define the arg for `dynamic` function. This arg has specified structure:
```
abstract class DynamicOperation extends JsonClass {
...
  DynamicOperation({
    required this.template,
    required this.target,
    required this.values,
  });
  
  DynamicOperationType get type;
  ...
  
  class AddDynamicOperation extends DynamicOperation {
  static const values_id_key = 'id';

  AddDynamicOperation(
      String template, Map<String, dynamic> target, Map<String, dynamic> values)
      : super(template: template, target: target, values: values);

  @override
  DynamicOperationType get type => DynamicOperationType.ADD;
  ...}
```

For that the best is to use `set_value` type.
* `type` - add/remove/edit are supported
* `template` - the id of dynamic widget on which the operation will be performed
* `target` - used to find the `index` so where to put new child. Adding `"index":-1` means to add this to the end of the children list. Current children values are taken from the registry values (dynamic component is putting the children values under its `id` key)
* `values` - newly added values. `id` if not provided will be always generated as the uuid. In this example the `message` is equal to a value of `form_message` varible.

3. The last action is to add the function trigger which will use the defined value
`"onPressed":"##dynamic(dynamicItemsAdd)##"`

That's it - now we have a situation in which after writing some text and clicking on the `Add message` button - we are seeing dynamically added messages to the list view.

### How to delete dynamic item?
Now we can start the real thing regarding this idea - because we are able to define actions on not yet existed element which ID we are not even know. We can do such a thing inside of `childTemplate`

```
{
  "type":"set_value",
  "args":{
    "remove{id}Element":{
      "type":"remove",
      "template":"items",
      "target":{
        "id":"{id}"
      }
    }
  },
  "child":{
    "id":"{id}",
    "type":"list_tile",
    "args":{
      "onLongPress":"##dynamic(remove{id}Element)##",
      "title":{
        "type":"text",
        "args":{
          "text":"{message}"
        }
      }
    }
  }
}
```

* ` "remove{id}Element"` - inside of `childTemplate` we can use `id` param to create the unique variable name
*  `"type":"remove"` - to define `remove` type of dynamic operation
* `"template":"items",` - the dynamic widget id - which is keeping children data in registry under this id
* `"target":{"id":"{id}"}` - child index will be found by finding the first child which id is equal to the one inside of child
* `"onLongPress":"##dynamic(remove{id}Element)##"` - remove function is triggered by the long press

Using the `id` param inside of templated is giving us a lot of possibilities by defining the set of relations and by giving the unique for every element

### How to edit dynamic item?
That technique is the same as in `remove` operation with a difference that this is giving us a possibility to modify the content.
I've used for that `show_dialog` function which is pretty basic one (I do not know if do you wanna sth like that)

Soo again inside of `childTemplate`
```
{
  "type":"set_value",
  "args":{
    "edit{id}Element":{
      "type":"edit",
      "template":"items",
      "target":{
        "id":"{id}"
      },
      "values":{
        "message":"{{edit_message_{id}}}"
      }
    },
    "editDialogData{id}":{
      "actions":[
        {
          "title":{
            "type":"text",
            "args":{
              "text":"Submit"
            }
          },
          "onPressed":"##dynamic(edit{id}Element)##"
        }
      ],
      "title":{
        "type":"text",
        "args":{
          "text":"Edit"
        }
      },
      "content":{
        "type":"form",
        "child":{
          "type":"single_child_scroll_view",
          "args":{
            "padding":[
              16,
              0
            ]
          },
          "child":{
            "type":"container",
            "args":{
              "alignment":"topCenter",
              "width":"infinity"
            },
            "child":{
              "type":"text_form_field",
              "id":"edit_message_{id}",
              "args":{
                "initialValue":"{message}",
                "decoration":{
                  "hintText":"Write a message"
                },
                "validators":[
                  {
                    "type":"required"
                  }
                ]
              }
            }
          }
        }
      }
    }
  },
  "child":{
    "id":"{id}",
    "type":"list_tile",
    "args":{
      "trailing":{
        "type":"icon_button",
        "args":{
          "icon":{
            "type":"icon",
            "args":{
              "icon":{
                "codePoint":59109,
                "fontFamily":"MaterialIcons",
                "size":50
              }
            }
          },
          "onPressed":"##show_dialog(dialogContext, editDialogData{id})##"
        }
      },
      "title":{
        "type":"text",
        "args":{
          "text":"{message}"
        }
      }
    }
  }
}
```

* "edit{id}Element" - defines the edit operation data. It uses ` "message":"{{edit_message_{id}}}"` as the new message.
* `"editDialogData{id}"` - defines the variable which contains information about how the dialog should looks like. It contains actions, title and content section
* `editDialogData{id}.actions` - here the dynamic edit function is triggered via (`"onPressed":"##dynamic(edit{id}Element)##"`)
* `editDialogData{id}.content` - in here there`s `text_form_field` defined which is updating `"edit_message_{id}` value (used in edit operation)
*  `"onPressed":"##show_dialog(dialogContext, editDialogData{id})##"` - dialog showing is using `dialogContext` variable saved via  `save_context` element and `editDialogData{id}`  and is triggered via pressing on the icon.

## Summary
So as you can see the `dynamic` component is giving the possibility to recursively define set of dynamic actions. It is giving the recipe how the future object relations should looks like and how the children should behave.

I'm waiting on your opinion on the implementation details. Is there sth that you would like to change? 
The tests were not written yet I'm also pretty new in a Flutter so this will take me longer :D 

I'm really enjoying your project idea :)  Hope that this `dynamic` thing will be sth that will help your project to grow even more :)

**Comment by jpeiffer** [comment]
Wow, I really like it.  It's a very clever usage of the library, and a great addition.  As a concept it looks great.  I can give more specific feedback via a PR, but the high level definitely has my support.

**Comment by kperchlicki** [comment]
Nice :)
I'll then start the work on PR and we'll continue discussion on the code level in there :)

**Comment by jpeiffer** [comment]
No rush at all.  Just posting to let you know I'm actively watching.

**Comment by kperchlicki** [comment]
Ok - I'm working slowly but steady 😁

**Comment by kperchlicki** [comment]
The work on it is done - I need to get write access to push the commit

**Comment by jpeiffer** [comment]
Oh, the typical way to contribute to an OSS repo is to fork it, then make a PR from your fork.  Granting direct write access usually doesn't happen.

You can fork the repo, copy your changes in there, commit & push, then create a PR.  The validators will then run and give you feedback.

**Comment by jpeiffer** [comment]
PR merged and deployment happening.  Thanks for the great contribution.

**Comment by kperchlicki** [comment]
You're welcome!

PS: Whoops sth gone wrong with the build
https://github.com/peiffer-innovations/json_dynamic_widget/runs/3526305009

**Comment by kperchlicki** [comment]
I've fixed that in https://github.com/peiffer-innovations/json_dynamic_widget/pull/31
