### ISSUE TITLE
Issue with dropdown_button_form_field

### ISSUE THREAD

**Issue by naveen715** [peiffer-innovations/json_dynamic_widget#287]
`{
                    "type": "set_value",
                    "args": {
                      "values": {
                        "index": ["abc","pqr","stu"]
                      },
                      "child":{
                        "type": "expanded",
                        "args": {
                          "child": {
                            "type": "dropdown_button_form_field",
                            "listen": [
                              "index"
                            ],
                            "args": {
                              "decoration": {
                                "labelText": "Select Island"
                              },
                              "items":"${index[0]}",
                              "validators": [
                                {
                                  "type": "required"
                                }
                              ]
                            }
                          }
                        }
                      }
                    }
                  }`
creating a dropdown with dynamic items throws errror 
Another exception was thrown: NoSuchMethodError: Class 'String' has no instance method 'forEach'.
How can i correctly use dropdown_button_form_field with dynamic items.

**Comment by crisperit** [comment]
```
"items":"${index[0]}"
```

You probably should place in here the whole array instead of the single element of that array

**Comment by naveen715** [comment]
No that also doesn't work 

The following NoSuchMethodError was thrown building
_JsonWidgetStateful-[<'json_widget_stateful.5f9aaa94-78b3-4c52-beb4-e66ea587a918'>](state:
_JsonWidgetStatefulState#c4269):
Class 'String' has no instance method 'forEach'.
Receiver: "${index}"
Tried calling: forEach(Closure: (dynamic, dynamic) => Null)

The relevant error-causing widget was:
  _JsonWidgetStateful-[<'json_widget_stateful.5f9aaa94-78b3-4c52-beb4-e66ea587a918'>]
  _JsonWidgetStateful:file:///C:/Users/nkt88/AppData/Local/Pub/Cache/hosted/pub.dev/json_dynamic_widget-7.0.6+5/lib/src/builders/json_widget_builder.dart:62
  :16

When the exception was thrown, this was the stack:
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:38:5)
#1      _JsonDropdownButtonFormFieldWidgetState._getItems (package:json_dynamic_widget/src/builders/json_dropdown_button_form_field_builder.dart:546:22)    
#2      _JsonDropdownButtonFormFieldWidgetState.initState (package:json_dynamic_widget/src/builders/json_dropdown_button_form_field_builder.dart:483:14)    
#3      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5611:55)
#4      ComponentElement.mount (package:flutter/src/widgets/framework.dart:5456:5)
...     Normal element mounting (23 frames)
#27     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4335:16)
#28     MultiChildRenderObjectElement.inflateWidget (package:flutter/src/widgets/framework.dart:6893:36)
#29     MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6905:32)
...     Normal element mounting (28 frames)
#57     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4335:16)
#58     MultiChildRenderObjectElement.inflateWidget (package:flutter/src/widgets/framework.dart:6893:36)
#59     MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6905:32)
...     Normal element mounting (113 frames)
#172    Element.inflateWidget (package:flutter/src/widgets/framework.dart:4335:16)
#173    Element.updateChild (package:flutter/src/widgets/framework.dart:3840:20)
#174    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505:16)
#175    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5643:11)
#176    Element.rebuild (package:flutter/src/widgets/framework.dart:5196:7)
#177    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2904:19)
#178    WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:989:21)
#179    RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:448:5)
#180    SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1386:15)
#181    SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1311:9)
#182    SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:1169:5)
#183    _invoke (dart:ui/hooks.dart:312:13)
#184    PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:399:5)
#185    _drawFrame (dart:ui/hooks.dart:283:31)

I have pasted the entire error log for your reference 
if you can please provide a sample of dropdown_button_form_field using set value or dynamically getting data for items. @crisperit @jpeiffer
