### ISSUE TITLE
Feature Request : Create form widget from JSON schema

### ISSUE THREAD

**Issue by nilesh-darji** [peiffer-innovations/json_dynamic_widget#288]
**Great project**

**Idea**
Create from widget from JSON schema

- JSON schema has validation so we can use those validations for form validations.

**Comment by crisperit** [comment]
Validation is probably handled by https://github.com/peiffer-innovations/form_validation lib e.g. https://github.com/peiffer-innovations/json_dynamic_widget/blob/main/json_dynamic_widget/example/assets/pages/form.json#L208-L215

Reopen if it's not enough in you opinion
