### ISSUE TITLE
Assistance on using set_value

### ISSUE THREAD

**Issue by naveen715** [peiffer-innovations/json_dynamic_widget#291]
Below is a example of set_value that i am using to display data from a map 
`{
  "type": "set_value",
  "args": {
    "values": {
      "entries": {
        "values": [
          {
            "DATE": "04/06/2024",
            "TIME": "14:43:03",
            "SERVICENAME": "Reload",
            "AMOUNT": "MVR 1",
            "AMOUNTSTR": [],
            "DESCRIPTION": "Self Recharge",
            "DRCRFLAG": "1",
            "TRANSID": "1688812415652983",
            "STATUS": "Failed",
            "STATUSFLAG": "2",
            "SOURCEPARTY": "7782945",
            "DESTPARTY": "7782945",
            "S_NAME": "AHMED HAANEE ABDUL RAHMAN",
            "D_NAME": "AHMED HAANEE ABDUL RAHMAN",
            "MSGMODE": "APP",
            "S_MSG": "Requested Prepaid Topup Amount is less than defined limit value.Prepaid Topup of MVR1cannot be processed. TID:1688812415652983 ",
            "SERVICEID": "12",
            "TRANSTYPE": "1"
          },
          {
            "DATE": "04/06/2024",
            "TIME": "11:12:09",
            "SERVICENAME": "Reload",
            "AMOUNT": "MVR 1",
            "AMOUNTSTR": [],
            "DESCRIPTION": "Self Recharge",
            "DRCRFLAG": "1",
            "TRANSID": "2287362415640329",
            "STATUS": "Failed",
            "STATUSFLAG": "2",
            "SOURCEPARTY": "7782945",
            "DESTPARTY": "7782945",
            "S_NAME": "AHMED HAANEE ABDUL RAHMAN",
            "D_NAME": "AHMED HAANEE ABDUL RAHMAN",
            "MSGMODE": "APP",
            "S_MSG": "Requested Prepaid Topup Amount is less than defined limit value.Prepaid Topup of MVR1cannot be processed. TID:2287362415640329 ",
            "SERVICEID": "12",
            "TRANSTYPE": "1"
          }
        ]
      },
      "template":{
            "type": "list_tile",
            "args": {
              "subtitle": {
                "type": "text",
                "listen": ["value"],
                "args": {
                  "text": "${value[STATUS]}"
                }
              },
              "title": {
                "type": "text",
                "listen": ["value"],
                "args": {
                  "text": "${value[DATE]}"
                }
              }
        }
      }
    },

{
                    "type": "expanded",
                    "listen": [
                      "entries"
                    ],
                    "args": {
                      "child": {
                        "type": "list_view",
                        "args": {
                          "children": "${for_each(entries['values'], 'template')}"
                        }
                      }
                    }
                  }`
But the above implementation doesn't work nor it gives any error please inform about correct method to get data from values and display it within templates

**Comment by suvidhapatekar-blitz** [comment]
I'm facing the same issue. Can you please help me solve this? I'm stuck here.
