### ISSUE TITLE
Big Problem with Lists

### ISSUE THREAD

**Issue by Thauanny** [peiffer-innovations/json_dynamic_widget#294]
basically its when we are dealing with List. check the print bellow. Imagine the we have a Entity called `FAQItem` and a `List<FAQItem>` on my widget atributtes.
the .g does not convert it to a `List<FAQItem>` when reading the json. Resulting an error.

And its not only with `List<Entity>`, it's with every list.
`List<String>`, `List<Int>`...
I have to put manually `List.from(map["list_example"])`.

or in the case of `List<Entity>`:

<img width="611" alt="faq_example" src="https://github.com/peiffer-innovations/json_dynamic_widget/assets/44787914/c75e404b-260e-4072-8d17-c5bc3549aa8e">

I check the examples but there's no example using those kind of lists
there's a alternative for don't manually edit the .g file?

**Comment by crisperit** [comment]
Responded in here
https://github.com/peiffer-innovations/json_dynamic_widget/issues/260#issuecomment-2148293288

Closing that one
