### ISSUE TITLE
Can't find the way/guide to export json with listen variables, Please help me.

### ISSUE THREAD

**Issue by comk** [peiffer-innovations/json_dynamic_widget#302]
I do find the "listen" propertis in the json, But I didn't find the way to set the listen variable to JsonXXX widget. 
I read the guide doc, But I didn't find how to set listen variables and how to export a listen variables.
So I can't export a json with a "listen" propertis.
Please help. 
Thanks

**Comment by crisperit** [comment]
What do you mean that you cannot set listen variable? Do you mean that the  code created with
https://github.com/peiffer-innovations/json_dynamic_widget/blob/main/json_dynamic_widget/lib/src/builders/json_exportable_builder.dart not supports specifying `listen` set?

If that's what you mean - then yeah it is not supported aand that might be a good idea to add such a possibility. Feel free to open your PR :D

**Comment by comk** [comment]
Thank for your reply!
``` json
"listen": [
            "slow_middle_curve",
            "customOpacity"
          ],
```
I mean, how can I include the listen property node in jsonstring with json_exportable_builder?
I found the generated toJson method of JsonXXX, It doesn't include the listen property, so this makes me confused.

**Comment by crisperit** [comment]
You cannot at this moment. For now you can only export the json and then add these `listen` vars to the json manually..

Fell free to open your PR with the missing functionality

**Comment by comk** [comment]
Thank for your reply, I'll have a try on it in my free time.
