### ISSUE TITLE
How to started 

### ISSUE THREAD

**Issue by golfziller** [peiffer-innovations/json_dynamic_widget#307]
I'm testing the library but I can't genarate the code after using the command **" flutter pub run build_runner build --delete-conflicting-outputs"** Do I need to do anything earlier?

[√] **Flutter (Channel stable, 3.19.1, on Microsoft Windows [Version 10.0.19045.4651], locale th-TH)**
[√] **Windows Version (Installed version of Windows is version 10 or higher)**

[√] **Chrome - develop for the web**

[√] **Android Studio (version 2021.2)**
[√] **VS Code (version 1.91.1)**
[√] **Connected device (3 available)**
[√] **Network resources**

![image](https://github.com/user-attachments/assets/6fd0ae07-230c-457c-aba1-85287efb4565)
![image](https://github.com/user-attachments/assets/8b562a41-e71b-4ff3-8fad-8100d4e0cf3a)

**Comment by crisperit** [comment]
I think that you need to have Flutter v3.22

**Comment by golfziller** [comment]
Added package  **json_dynamic_widget_codegen**  it work
https://pub.dev/packages/json_dynamic_widget_codegen
