### ISSUE TITLE
Thanks for your response, but I need to add a new button in my json at the time my newly added button onTap function is not registered in my  live app or apk, so give an error because of function not registered . That's why I'm asking that registerFunctions also dynamically register. I don't know if this is possible; if possible, please guide me. 

### ISSUE THREAD

**Issue by vijaymsc** [peiffer-innovations/json_dynamic_widget#309]
Thanks for your response, but I need to add a new button in my json at the time my newly added button onTap function is not registered in my  live app or apk, so give an error because of function not registered . That's why I'm asking that registerFunctions also dynamically register. I don't know if this is possible; if possible, please guide me. 
@crisperit @jpeiffer

_Originally posted by @vijaymsc in https://github.com/peiffer-innovations/json_dynamic_widget/issues/299#issuecomment-2247727813_

**Comment by crisperit** [comment]
Better to reopen the closed one than create the new issue..
