### ISSUE TITLE
need to deal with build errors without breaking the entire view

### ISSUE THREAD

**Issue by Thauanny** [peiffer-innovations/json_dynamic_widget#311]
need to deal with build errors without breaking the entire view.

I opened this PR because of this need.
A small change to deal with this lack of being able to deal with errors in a more customized way.

Please check bellow:

https://github.com/peiffer-innovations/json_dynamic_widget/pull/310

**Comment by crisperit** [comment]
Nice - good idea to add such a callback 

What do you think @jpeiffer ?

**Comment by jpeiffer** [comment]
This is deployed as of now.
