### ISSUE TITLE
Make Align widget take custom alignment values

### ISSUE THREAD

**Issue by OgieBen** [peiffer-innovations/json_dynamic_widget#32]
According to this [doc](https://pub.dev/documentation/json_theme/latest/json_theme/ThemeDecoder/decodeAlignment.html) the Align widget only supports the following values:

- bottomCenter
- bottomLeft
- bottomRight
- center
- centerLeft
- centerRight
- topCenter
- topLeft
- topRight

It might be good to have this widget support "x" and "y" coordinate values as its args values instead of just the predefined values.

Sample:
        `{
          "type": "align",
          "args": {
            "alignment": {
              "x": "-0.4",
              "y": "1"
            }
          },
          "child": {
            "type": "container",
            "args": {
              "color": "#E1BEE7",
              "padding": 16
            },
            "child": {
              "type": "text",
              "args": {
                "text": "topCenter"
              }
            }
          }
        }`

**Comment by jpeiffer** [comment]
I'm going to close this issue as it's on the wrong repo.  Feel free to open it against the [json_theme](https://github.com/peiffer-innovations/json_theme) one though.  Granted, I maintain both, and like the suggestion.  It's more for my own sanity to have the things in the right places when I make updates.  :)

**Comment by jpeiffer** [comment]
Also, I got bored and had another fix I needed to deploy tonight anyway so... use 3.0.1 of `json_theme` and you can now pass your JSON through.

If you have any issues though, please do open them against `json_theme` if it's related to this.
