### ISSUE TITLE
Issue with dropdown_button_form_field

### ISSUE THREAD

**Issue by tjanhvi** [peiffer-innovations/json_dynamic_widget#320]
I want to implement a user interface with the following features:

Color Cards: Display a horizontal list of color cards (e.g., blue, green, yellow). Each card represents a different color.

Dropdown Menu: Below the color cards, provide a dropdown menu that lists different sizes.

Requirements:

When a user selects a color card, the dropdown menu should automatically update to display the size corresponding to the selected color.
Specifically, the dropdown menu should default to the 0th index value (i.e., the first item) when a new color is selected.
The dropdown should be dynamically updated based on the selected color, ensuring that any interaction with the color cards reflects appropriately in the dropdown menu.
Desired Behavior:

Color Selection: Clicking on a color card updates the dropdown menu to reflect the first size option associated with that color.
Size Selection: After selecting a color and the dropdown updates, the user can then select a size from the dropdown menu.

**Comment by jpeiffer** [comment]
This seems like a question better for StackOverflow as it is not an issue with the package itself.
