### ISSUE TITLE
Updating Card Selection Dynamically in a ListView Using JSON

### ISSUE THREAD

**Issue by tjanhvi** [peiffer-innovations/json_dynamic_widget#323]
In a ListView, I want to display a list of cards with their names. When a card is selected, I want to capture the card name and update it in a registry. Additionally, this updated name should be reflected in the JSON data used by the ListView.

**Comment by jpeiffer** [comment]
This seems like a question better for StackOverflow than here as it is not an issue with the package itself.  I suggest you try there.
