### ISSUE TITLE
Dynamic JSON Equivalent for Flutter's Visibility Widget

### ISSUE THREAD

**Issue by tjanhvi** [peiffer-innovations/json_dynamic_widget#324]
In Flutter, we use the Visibility widget to control the visibility of a child widget. What is the equivalent approach to achieve the same functionality when building widgets dynamically from JSON?

**Comment by jpeiffer** [comment]
Added the `Visibility` widget with 7.3.1.

Example here:
https://github.com/peiffer-innovations/json_dynamic_widget/blob/main/json_dynamic_widget/example/assets/pages/visibility.yaml
