### ISSUE TITLE
Adding JSON Dynamic Widget Helper Extension to README

### ISSUE THREAD

**Issue by cem256** [peiffer-innovations/json_dynamic_widget#332]
I developed a VS Code extension called `JSON Dynamic Widget Helper`, which simplifies working with `json_dynamic_widget` by providing options to wrap and remove widgets directly within the JSON. I believe including it in the README would be beneficial to the community

[Marketplace](https://marketplace.visualstudio.com/items?itemName=cem256.json-dynamic-widget-helper)
[Repository](https://github.com/cem256/json-dynamic-widget-helper)

Short demo
![usage](https://github.com/user-attachments/assets/19218948-09a4-4ff4-968d-48b7747d2257)

**Comment by crisperit** [comment]
Really cool - thanks for that extension!
