### ISSUE TITLE
Add JS execution plugin

### ISSUE THREAD

**Issue by crisperit** [peiffer-innovations/json_dynamic_widget#38]
### WHAT?
Add a general support to execute JS code - like: `##js(new Date().toISOString())##` - with an usage of https://pub.dev/packages/flutter_js

### WHY?
* Instead of defining a lot of simple functions like ##currentDateISO()##, ##add(1,2)## we can easily in such a way add a really powerful tool - JS in the hands of library users
* To add more possibilities - without a need to define countless custom functions

**Comment by jpeiffer** [comment]
The JS library has a sizable increase to the final build size.  I'm not interested in adding that dependency to this core library.  It'd come with too much of a cost to only benefit a subset of the users.

That said, the framework is purposefully pluggable.  This sounds like it'd be a great plugin opportunity
