### ISSUE TITLE
Add a component builder type

### ISSUE THREAD

**Issue by crisperit** [peiffer-innovations/json_dynamic_widget#39]
### What
Proposed `component` being will be defined in the JSON format. It will contain json widget data definition - with an interface and its own name. Such a file with a component definition can be kept as the asset or can be available under some URL - and the component bulder will be introduced as a way to use such a components to compose the final view.

I think that the whole idea behind that can be shown on some example. (Be aware that proposed in the example format is sth to be discussed).

So let's say that we have a really big microservices system with over 300 services. Each of the services is returning to the Flutter app the views in JSON format (json_dynamic_widget).
The biggest challenge is to maintain that the views returned from such a big amount of services will look the same. 

So for example every service uses submit button like that:
```
 {
       "type": "raised_button",
        "id": "submit_button",
         "args": {
             "color": "#4a95ec",
              "colorBrightness": "dark",
          },
          "child": {
               "type": "text",
                "args": {
                      "text": "Submit"
                 }
           }
}              
```

Buut let's say that we are changing our app view - and from now on we want completely different submit button look.
What does it means for such an infrastructure? 300 services has to make a release and change every submit button manually in every view. Most scary is the need to synchronize such a releases 

We have of course some ways - like to define some variables or create custom builder types. Buut I want to introduce a different approach.

So the flutter app can keep such a submit button defined and keep that on apps side - like:

`/components/1.0/submit_button.json`
```
{
   # name of the component
   "name": "submit_button",
   # params definitions and validation details
   "params": {
       "text": {
            "type": "string",
            "min_length": 1
        }
   },
   # json dynamic widget definition with args putted in {}
   "data": {
       "type": "raised_button",
        "id": "submit_button",
         "args": {
             "color": "#8aff8a",
              "colorBrightness": "dark",
          },
          "child": {
               "type": "text",
                "args": {
                      "text": "{text}"
                 }
           }
   }
}              
```

Then all of these 300 services can use that via component builder like that:

```
{
   "type": "component",
   "args": {
       "name": "submit_button",
       "version": 1.0,
       "params": {
            "text": "Submit"
        }
   }
}
```

Let's say that in the registry we will have a possibility to define a path / url for components - to keep it simple.

### Why?
* To add an easy way to build custom components without a need to touch the dart code
* To reduce backend payload size (if backends will only send components definitions then the payload will decrease drastically)
* To give a powerful tool for micro-frontends architectures
* To be able to create easy to maintain views (components can be created and maintained via frontend team) aand the backend teams which do not know how to create good views can only used well defined components

@jpeiffer 
I know that sth like components might be replaced somehow via custom defined builders. I would like to give an easy way for that without any dart code changes - let's say an alternative to define custom builders way :)

**Comment by jpeiffer** [comment]
This sounds like it is just a variable by a different name.  I'm not sure I see the benefit of the component when it's effectively just a variable by a different name.

In the app's bootstrap code it could download a "variables map" from the service once and wire those variables up.  Or if the variables are local, have a `variables.json` that gets loaded in.

There would need to be Dart code to load in the components.  Which isn't really different then needing some Dart code to bind the variables however you'd like.

**Comment by crisperit** [comment]
Well I do not think that the components concept can be replaced via variables. 

Let's say that you'll save somehow
```
{
       "type": "raised_button",
        "id": "submit_button",
         "args": {
             "color": "#8aff8a",
              "colorBrightness": "dark",
          },
          "child": {
               "type": "text",
                "args": {
                      "text": "{{text}}"
                 }
           }
   }
```
To the variable `submit_button` and load to the flutter app. How can you load such a JsonWidgetData from the variable?


Additionally even if you'll be able to load the widget from the variable - then you cannot parameterize that correctly.
Let's say we want to parameterize the widget under `submit_button` with some `{{text}}`

Well if there is only 1 `submit_button` rendered then setting the var `{{text}}` will be good enough. But what if we wanna to have 2 `submit_button` rendered with different texts? Or what if the other place is using `{{text}}` as a variable. The component idea is giving some nice encapsulation concept.


For me the components is more similar to custom builders created from the existing ones. It uses these builders inside in some way and expose the interface to configure such a set of widgets

What do you think?

**Comment by jpeiffer** [comment]
Even from this example, I'm not sure I'm seeing the value though.  If the JSON is rendered from the back end, having two buttons with two different `{{text}}` variables, it's not really that hard.

Asset based widgets are not at all the point of this repo.  It is very much intended to be server side rendered, even if assets are the examples.

On a server side render, having two sets of raised buttons should be a non-issue.  And if it is an issue, that feels like it's a problem more targeted at the server level rather than the library one.

**Comment by crisperit** [comment]
Yeah if there is only 1 server which is rendering the jSONs - then there is definitely not problem and the library is perfect for that.

I'm trying mostly to propose an additional builder (which can be used or not - library is not about forcing the conventions) to help to deal with such a use-case. 

Asset based widget is actually just equal to user defined bilder - but with a form of JSON

Well this is just an extension and possibility to declare components in a different way.

If you think that this builder will affect the library in a wrong direction - then we can close this issue. 
You are the leader :D

**Comment by jpeiffer** [comment]
I think a better approach would be to improve either the variable or function syntax as opposed to adding a net new concept.

If you have suggestions or ideas for that type of improvement, I'm all ears.  I know the current one is "overly simple" and a bit awkward because it was quick to implement over "easy to use".

**Comment by crisperit** [comment]
Maybe I can also do such a component builder type as a plugin?
