### ISSUE TITLE
JSON migration tools

### ISSUE THREAD

**Issue by crisperit** [peiffer-innovations/json_dynamic_widget#48]
Between the versions of `json_dynamic_widget` - and versions of Flutter itself very often there is a situation that some particular field names are changing its names or values.

I wonder if we cannot create some kind of tool - released always along with new versions of library which will migrate users JSON widgets into new version?

**Comment by jpeiffer** [comment]
This would be cool.  My overall philosophy is to support both when possible.

It's pretty rare that the Flutter team simply renames something.  Usually it's they add something, or deprecate something old while adding the new one in a somewhat incompatible (and thus hard to automatically transform to) way.

**Comment by jpeiffer** [comment]
Closing as stale issue.
