### ISSUE TITLE
URLs (`$id` field) returning 404 (not found)

### ISSUE THREAD

**Issue by pfeodrippe** [peiffer-innovations/json_dynamic_widget#49]
Hi, the URLs (`$id` field) for the schemas https://github.com/peiffer-innovations/json_dynamic_widget/blob/main/lib/src/schema/schemas/measured_schema.dart and https://github.com/peiffer-innovations/json_dynamic_widget/blob/main/lib/src/schema/schemas/layout_builder_schema.dart are returning 404 (the other schemas are working).

Thanks for this project, it's awesome o/

**Comment by jpeiffer** [comment]
Yep, seems I missed those.  The release posted a few minutes ago fixes them.  Thanks for letting me know.

**Comment by pfeodrippe** [comment]
Thanks!
