### ISSUE TITLE
Infinite Scrolling ListView

### ISSUE THREAD

**Issue by smiLLe** [peiffer-innovations/json_dynamic_widget#50]
Hi :) I just found this library and i just did a few smaller testings. But now i am kinda stuck. I want to build a ListView (like facebook feed ..) which can load data from remote and then display (append) the newly fetched data. But i am not sure how to achieve this.
I need to somehow tell this lib to execute a callback ( fetch new data ) after reaching the end of the listview and make the callback somehow append the new data to the current ListView. 

Perhaps someone else got the same problem/idea and already solved it :)

**Comment by jpeiffer** [comment]
My first question is why can't each list item be a unique dynamic widget?  Then you could just load the data in a standard `ListView` and listen to when you get to the threshold to load more.  That's probably the easiest path forward.  This approach would likely be more performant as well.

But... if that doesn't work, you can bind a custom widget to the registry that knows when it is rendered.  Keep track of how many of them have been rendered and use that as your trigger for loading more data and replacing the variable you used for the children of the `list_view`. The `list_view` only renders widgets within the viewport, or near the viewport, so if you put, say 100, widgets in the list, but they are standard card sized widgets, only 3-5 (depending on screen size) will actually render initially.  The rest will render when they are scrolled to and that can be your que.
