### ISSUE TITLE
form.json example strange behaviour

### ISSUE THREAD

**Issue by maratkalibek** [peiffer-innovations/json_dynamic_widget#53]
Text cannot by typed to the form. Text typed to `text_form_field` being deleted after each 2 chars.

Logs show only current output - `I/IMM_LC  ( 8330): ssi() view is not EditText`.

json_dynamic_widget version = ^4.1.1+1

**Comment by cristopher-ozone** [comment]
Hello, could you post some reproduceable example (for example your JSON with the view + pubspec)

**Comment by crisperit** [comment]
Hello, could you post some reproduceable example (for example your JSON with the view + pubspec)

**Comment by jpeiffer** [comment]
Closing as stale issue.
