### ISSUE TITLE
handle click button not working

### ISSUE THREAD

**Issue by ahmedjedidi** [peiffer-innovations/json_dynamic_widget#58]
i'm using flat button and when i click on it nothing is shown in the console.
My code:
```json
 "child": {
                   "type": "flat_button",
                    "args": {
                            "onPressed": "${log('my message', 'info')}",
                  },
                            
```

**Comment by crisperit** [comment]
Yeah you're right - I've added the PR with the the fix for that issue

**Comment by ahmedjedidi** [comment]
still not working

**Comment by cristopher-ozone** [comment]
It is working for me - please sent the whole JSON of your view + check whenever you've get newest dependency
![image](https://user-images.githubusercontent.com/58423528/173871162-8627cf23-48d3-44f2-ba51-67bbda5966e3.png)

**Comment by ahmedjedidi** [comment]
``{
    "type": "scaffold",
    "args": {
        "appBar": {
            "type": "app_bar",
            "args": {
                "title": {
                    "type": "text",
                    "args": {
                        "text": "ACCEUIL",
                         "style": {
                    "color": "#000000",
                    "fontSize": 18
                  }
                    }
                },
                "centerTitle":true,
                "backgroundColor":"#fff",
                "elevation":0
            }
        },
        "body": {
            
             "type": "single_child_scroll_view",
        "child": {
            "type": "column",
            "children": [

                {
                    "type": "padding",
                    "args": {
                    "padding": {
                      "bottom": 10,
                      "top":10,
                      "left":10,
                      "right":10
                    }
                  },
                  "child": {
                    "type": "clip_rrect",
                    "args": {
                      "borderRadius": {
                        "type": "circular",
                        "radius": 60
                      }
                    },
                    "child":{
                "type": "container",
                "args": {
                  "width": "infinity",
                  "height":60,
                  "color":"#e2001a"

                },
                 
                  "child": {
                            "type": "flat_button",
                            "args": {
                                "onPressed": "${log('my message', 'info')}",
                                "color": "#e2001a" 
                            },
                            "child": {
                                "type": "text",
                                "args": {
                                    "text": "commander",
                                    "style": {
                    "color": "#fff",
                    "fontSize": 18
                  }
                                }
                    }
                  }
                }
                }}
                
                     
            ]
        }
    }
    }
}``json
i 'm using 'json_dynamic_widget: ^5.0.1+1' in pubspec.yml

**Comment by crisperit** [comment]
Well.. still working
![image](https://user-images.githubusercontent.com/17547300/173881975-1740d0e3-dfe6-4c74-b2ae-7c7a13a340c5.png)

Maybe sth has cached (?)

**Comment by ahmedjedidi** [comment]
maybe because i'm running with a simulator android?

**Comment by crisperit** [comment]
You should at least see the logs in a Flutter CLI

**Comment by jeff-peiffer-disney** [comment]
Or, try a physical device. Android emulators can be finicky.

**Comment by ahmedjedidi** [comment]
i will try thanks for your reply
