### ISSUE TITLE
exemple navigation 

### ISSUE THREAD

**Issue by ahmedjedidi** [peiffer-innovations/json_dynamic_widget#61]
is there any exemple using navigation with this method ${navigate_named('home', someValue)} ?

**Comment by crisperit** [comment]
I see no examples

By looking at docs the navigatorKey has to be provided

```
var navigatorKey = GlobalKey<NavigatorState>();

var registry = JsonWidgetRegistry.instance;
registry.navigatorKey = navigatorKey;
```

@jpeiffer might give you more detailed answer :)

**Comment by jpeiffer** [comment]
There's not an example right now but if you provide me with something you'd like to see I can create one pretty quickly.

Also, PRs are always welcome if you end up creating your own.
