### ISSUE TITLE
How get value from CheckBox?

### ISSUE THREAD

**Issue by samatzhusup** [peiffer-innovations/json_dynamic_widget#67]
and update current value

`{
                        "type": "cupertino_switch",
                        "args": {
                          "activeColor": "#2EB2FD",
                          "value": true,
                          "onChanged": "##myFunction(key:keyName, value:{{value}})##",
                        }
                      }`

**Comment by jpeiffer** [comment]
It looks like you are using the old templating syntax, so I'd first recommend moving to the new syntax as documented [here](https://github.com/peiffer-innovations/json_dynamic_widget#migration-to-4xx-version).

For any built in Form based widget that has an `id` field, the framework automatically provides you with code to get the value.  So updating your example...

```json
{
  "type": "row",
  "args": {},
  "children": [{
    "type": "cupertino_switch",
    "id": "my_switch_id",
    "args": {
      "activeColor": "#2EB2FD",
      "value": true
    }
  }, {
    "type": "conditional"
    "args": {
      "conditional": {
        "my_switch_id": true
      },
      "onFalse": {
        "type": "text",
        "args": {
          "text": "Not Checked"
        }
      },
      "child": {
        "type": "text",
        "args": {
          "text": "Checked!"
        }
      }
    }
  }]
}
```

You can see this in action in the `cupertino_switch` example and the respective [asset file](https://github.com/peiffer-innovations/json_dynamic_widget/blob/main/example/assets/pages/cupertino_switch.yaml).
