### ISSUE TITLE
registry.setValue is not working, simple example

### ISSUE THREAD

**Issue by Juweii** [peiffer-innovations/json_dynamic_widget#69]
Hello all,

I am pretty new to Flutter and try to play with a simple (the simplest) integration of json_dynamic_widget, but cant make it to work...
Generally the following sample works, except the value - it is not being changed and the output is just like `This is the variable: ${myVal}` instead of replacing myVal with the current registry.setValue value.

registry is been instanciated in my State<> class:
```
var registry = JsonWidgetRegistry.instance;
```

This is the widget within my scaffold:
```
JsonWidgetData.fromDynamic(
                  json.decode("""
                  {
                    "type": "text",
                    "args": {
                      "text": "This is the variable: \${myVal} "
                    }
                  }
                  """),
                  registry: this.registry,
                )!
                    .build(context: context)
```

This is how I try to change the value:
```
this.registry.setValue('myVal', 12345);
```

I expect that the `${myVal}`will be replaced by 12345, but that doesn't work..

The basic example of the Readme seems to be outdated and the navigate examples are just too complex for what I need.

Please guide me in the right direction.
Thanks,
Juergen

**Comment by crisperit** [comment]
Hello!

Try with:
`"text": "${'This is the variable:' + myVal}"`

And let know if that works
