### ISSUE TITLE
Shema error; anyOf violated

### ISSUE THREAD

**Issue by BartekDadas** [peiffer-innovations/json_dynamic_widget#75]
Hey,
I'm a junior programmer and recently started to working on a project that uses your library. Additionally I needed to render BottomNavigationBar from json and I know it's currently not supported so I tried to make builders for it myself following your examples,
but now I'm constantly getting same error no matter how many changes I make

> Schema Error: https://bartekdadas.github.io/schemas/bottom_nav_bar_schema.json
>  * [/properties/items/anyOf]: #/properties/items/anyOf: anyOf violated ([{bottomNavigationBar: {label: Icon1, icon: {type: icon, args: {icon: {codePoint: 57704, fontFamily: MaterialIcons}}}}}], [{type: string}, {type: array, items: {$ref: https://bartekdadas.github.io/schemas/bottom_nav_bar_item_schema.json}}])

Link to my repository with all  components  - https://github.com/BartekDadas/json_builder_example

**Comment by crisperit** [comment]
You are passing the `bottomNavigationBarItem` as
```
        {
          "bottomNavigationBarItem": {
            "label": "Icon1",
            "icon": {
              "type": "icon",
              "args": {
                "icon": {
                  "codePoint": 57704,
                  "fontFamily": "MaterialIcons"
                }
              }
            }
          }
        },
```

but basing on your schema you should pass it like:

```
          {
            "label": "Icon1",
            "icon": {
              "type": "icon",
              "args": {
                "icon": {
                  "codePoint": 57704,
                  "fontFamily": "MaterialIcons"
                }
              }
            }
          },
```

But it will only makes your schema pass and it still won't be working - cause you've created https://github.com/BartekDadas/json_builder_example/blob/main/lib/builders/bottom_navigation_bar_item_builder.dart

The builder expects the data to be passed via json as:
```
{
  "type": "bottom_navigation_bar_item",
  "args": {...},
}
```

I believe that finally your bottom_navigation_bar_itemjson should looks like that:

```
{
  "type": "bottom_navigation_bar_item",
  "args" : {
            "label": "Icon1",
            "icon": {
              "type": "icon",
              "args": {
                "icon": {
                  "codePoint": 57704,
                  "fontFamily": "MaterialIcons"
                }
              }
            }
          }
 },
 ...
```

And `SchemaHelper.objectSchema(JsonWidgetDataSchema.id)` should be used in schema def

**Comment by BartekDadas** [comment]
Thank you, for advice. Although fixing my model.json file didn't eliminated my problem.
I come up with a diffrent idea and get rid of JsonBottomNavigationBarItemBuilder.
There's still a lot of work with it, but at least now it's rendering


![Screenshot_20220825_214503](https://user-images.githubusercontent.com/80782193/186755364-d728d042-c352-40db-8314-8250b52860e7.png)
