### ISSUE TITLE
dynamic data 

### ISSUE THREAD

**Issue by shashikiran918** [peiffer-innovations/json_dynamic_widget#86]
how to render dynamic data in text widget ? because u given static data in  text widget  every json example.how to get dynamic data from url json which is coming from backend ?  if data changes after some point of time  how to change data every time  in json it is bad practice so that i want some example of dynamic data json  which is coming from backend ? please tell how to implement that?

**Comment by cristopher-ozone** [comment]
Hello - that's what `variables` are used for
https://github.com/peiffer-innovations/json_dynamic_widget#using-variables

```
{
  "type": "scaffold",
  "args": {
    "appBar": {
      "type": "app_bar",
      "args": {
        "title": {
          "type": "text",
          "args": {
            "text": "Dynamic var example"
          }
        }
      }
    },
    "body": {
      "type": "center",
      "child": {
        "type": "text",
        "args": {
          "text": "${backendText}"
        }
      }
    }
  }
}
```

So the view above is using `backendText` variable to provide the value for the text widget

If you will create some stateful widget which will async contact to the backend and call `registry.setValue('backendText', someDataFromBackend)` then the above view will rerender each time the value of `backendText` in the registry is changed

**Comment by crisperit** [comment]
Hello - that's what `variables` are used for
https://github.com/peiffer-innovations/json_dynamic_widget#using-variables

```
{
  "type": "scaffold",
  "args": {
    "appBar": {
      "type": "app_bar",
      "args": {
        "title": {
          "type": "text",
          "args": {
            "text": "Dynamic var example"
          }
        }
      }
    },
    "body": {
      "type": "center",
      "child": {
        "type": "text",
        "args": {
          "text": "${backendText}"
        }
      }
    }
  }
}
```

So the view above is using `backendText` variable to provide the value for the text widget

If you will create some stateful widget which will async contact to the backend and call `registry.setValue('backendText', someDataFromBackend)` then the above view will rerender each time the value of `backendText` in the registry is changed
