### ISSUE TITLE
How to properly use registered variable in JSON?

### ISSUE THREAD

**Issue by gredajustyna** [peiffer-innovations/json_dynamic_widget#89]
Hello,
I have been trying to render my widget tree using this package and as long as I hadrcode the values of e.g. text widget everything goes fine. However when i try to register the variable in registry and then use it in JSON as a reference, I get null. Before building my widget I check the content of registry and my variable is there. 

This is the part of my .json file:
```json=
          { 
          "type": "row",
          "args": {
            "mainAxisAlignment": "spaceBetween"
          },
          "children": [
            {
              "type": "text",
              "args": {
                "text": "${cinemaName}"
              }
            },
            {
              "type": "icon",
              "args": {
                "icon": {
                  "codePoint": 57369,
                  "fontFamily": "MaterialIcons"
                }
              }
            }
          ]
          },
```

in `initState` i assign json Data and registry:
```dart=
@override
  void initState() {
    super.initState();
    _data = JsonWidgetData.fromDynamic(widget.jsonData);
    _registry = widget.registry;
  }
```

`widget.registry` points to a registry initialized in a basic way: `var registry = JsonWidgetRegistry();`

This is the code I am using to build the widget tree:
```dart=
@override
  Widget build(BuildContext context) {
    _registry.setValue('cinemaName', 'Kinoxx');
    print(_registry.values);
    var widget = JsonWidgetData.fromDynamic(_data, registry: _registry);
    return widget!.build(context: context);
  }
```
And when I print the values, my output is `flutter: {cinemaName: Kinoxx}`. But in the rendered widget, in the place of this text i see `null`. How should I use the value set in registry?

**Comment by crisperit** [comment]
@gredajustyna Glad you've found it :)
