### ISSUE TITLE
RadioButton builder has only boolean values

### ISSUE THREAD

**Issue by munibz** [peiffer-innovations/json_dynamic_widget#93]
The radio builder sets the value of radios as false even after setting the values as string type in the Json will be attaching the screenshots of json as well as debug screenshot 

My reason being why it shouldn't set a Boolean value as I have seen it inside the builder the radio button builder has a dynamic type inference set on it 

if you have time, later can you make the radio button example using the registry to change the on changed value and making the radio button selectable, 

Also, I have been using this library for a month now have created some amazing lists using it even with Api data so thank you for that

![image](https://user-images.githubusercontent.com/81231153/195505987-01f46220-813d-4c89-83f2-1006c86198fc.png)

**Comment by cristopher-ozone** [comment]
Regarding the example:

You want to have the disabled radio button with the empty value let's say. 
And then you want to set the radio button value and enable it via registry set value call ?

**Comment by crisperit** [comment]
Regarding the example:

You want to have the disabled radio button with the empty value let's say.
And then you want to set the radio button value and enable it via registry set value call ?

**Comment by munibz** [comment]
> 

What I wanted to be demonstrated in the radio button example is to change the group value of the radio button using the on changed event in registry, which in return selects only a single radio button from say 4 radio buttons in the UI,

The one example which is there in theme.json uses only Boolean values and doesn't use on changed event to change the values between them

**Comment by crisperit** [comment]
Ok I've provided the fix + posted an example

@jpeiffer can you check it out?

**Comment by munibz** [comment]
Have checked the parseboolean line has been removed , thereby making the builder take dynamic values , closing it thanks for the help

**Comment by crisperit** [comment]
Np - we have to wait for that release a bit for @jpeiffer  :D
